### ISSUE TITLE
includeOnlyReactor: Update versions of only internal dependencies reachable from root in multi-module/reactor build

### ISSUE THREAD

**Issue by uvsmtid** [mojohaus/versions-maven-plugin#10]
This issue originates (copied & pasted) from [this stackoverflow question](http://stackoverflow.com/q/31579730/441652) - it might be a valuable feature for this plugin.
## Problem

When I run the following command for the `root` project, it checks for updates of ALL dependencies:

```
mvn versions:use-latest-versions
```

I want to limit versions update for only those dependencies which are reachable from the `root`:

```
    root/pom.xml
    ├── A/pom.xml
    │   └── D/pom.xml
    │       └── E/pom.xml
    ├── B/pom.xml
    └── C/pom.xml
        ├── F/pom.xml
        └── G/pom.xml
```
- Internal dependencies
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The group/artifact ids of these dependencies are in the current reactor build (multi-module build).
- External dependencies
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Any component with group and artifact ids which are not part of the build.
  
For example, I don **not** want to update external dependencies like `junit` or `commons-logging`.

There is an option **[`excludeReactor`](http://www.mojohaus.org/versions-maven-plugin/use-latest-snapshots-mojo.html#excludeReactor)**.  And I need an opposite like **`includeOnlyReactor`**.

Otherwise, it is unreliable and tedious work to specify all possible artifact patterns "managed" within sources being built via **[`includes`](http://www.mojohaus.org/versions-maven-plugin/use-latest-snapshots-mojo.html#includes)** option.

The problem is that changes in the internal dependencies are are controllable. External updates are not.

## Examples

For example, the following automatic update of external dependency just gets through unnoticed:

```
                    <dependency>                                                
                            <groupId>junit</groupId>                            
                            <artifactId>junit</artifactId>                      
    -                       <version>3.8.1</version>                            
    +                       <version>3.8.2-brew</version>                       
                            <scope>test</scope>                                 
                    </dependency>                                               
```

---

See also more clarifications in **[the comment below](#issuecomment-279229191)**.

**Comment by djbobyd** [comment]
I also need such a feature. Please consider implementing it.
Thanks!

**Comment by khmarbaise** [comment]
What about offering a PR ?

**Comment by khmarbaise** [comment]
It sounds you should use `mvn versions:set -DnewVersion=WhatEver` instead which will change the versions of all all modules incl. the parent in your multimodule build. So from my point of view it does not really makes sense to use latest-versions inside a multi module build.

**Comment by uvsmtid** [comment]
@khmarbaise, this is not the described use case. I believe `mvn versions:set -DnewVersion=WhatEver` simply sets exactly the same new version for all modules starting from parent (rather than updating the versions of dependencies). In other words, versions of dependencies have to be updated, not versions of the modules themselves. **The idea is to use the latest versions of dependencies** - fairly common update procedure.

Now, the dependencies can be split into two categories:
* (A) those which `groupId:artifactId` match those reachable from parent in multi-module reactor build
* (B) those which `groupId:artifactId` match those outside of reactor build (external dependencies)

For example:
* Any dependency like `A`, `B`, `C`, `D`, `E`, `F`, `G` and even `root` in the description are internal to the multi-module reactor build - they are in "category (A)". So, if `C` listed as dependency of `E`, its version (in dependency list) will be updated to the latest known non-snapshot version (because `C` is part of the same multi-module reactor build as `E`).
* Any dependency outside like `log4j:log4j` or `org.apache.camel:camel-core` will stay at the same versions because neither `log4j:log4j` or `org.apache.camel:camel-core` is being built starting from the `root` in the description.

Note that, in general, all those modules in example (`A`, `B`, `C`, `D`, `E`, `F`, `G` and even `root`) may actually have different release cycle (with completely different version numbers). The only thing in common they may have is that they are reachable from `root` (directly or indirectly) via `<module>` tag and, therefore, they are part of the same multi-module reactor build.

**Comment by khmarbaise** [comment]
Ok..misunderstanding on my site..

**Comment by iantipenkov** [comment]
I'd like to note that the suggested `includeOnlyReactor` flag would be useful with the `versions:set` goal as well, and perhaps others.
