### ISSUE TITLE
resolve-ranges does not handle ranges named in parent pom

### ISSUE THREAD

**Issue by jchesshir** [mojohaus/versions-maven-plugin#100]
This is similar to the problem in issue #16 , but it is different.

When the parent pom contains a dependency in dependency management that uses a version range, and when the child pom does not explicitly name its own version range, the resolve-ranges goal finds the proper version to substitute, but because it does not find the <version> tag, it outputs:

[WARNING] Could not find the dependency <artifact> so unable to set version to <version>

...where <artifact> is the name of the dependency and <version> is the proper version to resolve it to.
If this can't be fixed to just insert a new version tag into the dependency, the error should at least be more specific, like by saying:

[WARNING] Dependency version range for <artifiact> is from the parent pom, so cannot substitute the range with <version>.

But I think it should just be able to insert its own version tag in the dependency.

**Comment by khmarbaise** [comment]
Do you have an example project for this scenario?

**Comment by SvenssonWeb** [comment]
I'm not sure if anything happens with this issue but I have an example i want to share.

    <project>
        <groupId>this.group</groupId>
        <artifactId>this.parent</artifactId>
        <version>1.0.0</version>

        <dependencyManagement>
            <dependencies>
                <dependency>
                    <groupId>some.group</groupId>
                    <artifactId>some.artifact</artifactId>
                    <version>[1.0.0,2.0.0)</version>
                </dependency>
            </dependencies>
        </dependencyManagement>
    </project>

    <project>
        <parent>
            <groupId>this.group</groupId>
            <artifactId>this.parent</artifactId>
            <version>1.0.0</version>
        </parent>
        <artifactId>this.child</artifactId>

        <dependencies>
            <dependency>
                <groupId>some.group</groupId>
                <artifactId>some.artifact</artifactId>
            </dependency>
        </dependencies>
    </project>

In the above example the plugin will give the following warning for the child dependency:
[WARNING] Could not find the dependency some.group:some.artifact:jar:[1.0.0,2.0.0) so unable to set version to 1.0.2

The plugin should either set the version on all instances of the dependency, or just skip the ones with inherited version.

Although an issue arises when the parent is not part of the project and you skip the all inherited versions.

**Comment by khmarbaise** [comment]
After diving into this more I think the suggestion to remove the WARNING makes sense cause it only means the plugin has not found the `version` tag in pom file which will happen in the above described situations.
