### ISSUE TITLE
versions:set nextSnapshot is only working, when last number before -SNAPSHOT is zero-filled three digit.

### ISSUE THREAD

**Issue by rherschke** [mojohaus/versions-maven-plugin#101]
The code, used in SetMojo when running with `nextSnapshot = true` is only working, when the version of the project is in the format `x.y.zzz-SNAPSHOT`.

It assumes, that the "version" is a three-digit, zero filled Integer number (due to ominous magic number 3 in `substring(length-3)`), which leads to a NumberFormatException when running this with "normal" maven version patterns like 1.2.3-SNAPSHOT or even 1.2-SNAPSHOT and therefore this option is useless in most cases.

Please correct it by supporting all version formats.

Thx
Robert

**Comment by lion7** [comment]
I proposed a fix in https://github.com/mojohaus/versions-maven-plugin/pull/105

**Comment by OlaiSolheim** [comment]
I'm rooting for this. :)

**Comment by Frettman** [comment]
I registered at GitHub just to say how silly it is to assume that the last version segment has three digits. Not even the **versions-maven-plugin** follows that "convention". I hope this gets fixed soon, because I was happy to find the new feature...until it failed with a NumberFormatException :)

**Comment by timpeeters** [comment]
Great news that this has been fixed. Any idea when we might expect a new release of the plugin containing this fix?

Thanks in advance!

**Comment by foal** [comment]
Release?
