### ISSUE TITLE
update-property replaces square brackets

### ISSUE THREAD

**Issue by kartheekgurram** [mojohaus/versions-maven-plugin#104]
I defined a property

<properties>
        <mas.version>[1.0.0]</mas.version>
    </properties>

like this and I am using it as 

<dependency>
            <groupId>com.X.X.X.X</groupId>
            <artifactId>Base</artifactId>
            <version>${mas.version}</version>
        </dependency>

when I run this command
mvn versions:update-property -Dproperty=mas.version -DallowSnapshots=true -DnewVersion=[2.0.0-SNAPSHOT] -X 

<mas.version>[1.0.0]</mas.version> is replaced with <mas.version>2.0.0-SNAPSHOT</mas.version>.

The square brackets are gone and  versions:update-property is not working anymore.

**Comment by khmarbaise** [comment]
First why would you like to use `[2.0.0-SNAPSHOT]` ? Furthermore what do you mean by `and versions:update-property is not working anymore.`?
