### ISSUE TITLE
maven-version-plugin:2.3:use-latest-versions  replace ${xxx.version} placeholder 

### ISSUE THREAD

**Issue by johnnynemonic** [mojohaus/versions-maven-plugin#109]
When I use  versions:use-latest-versions (pligin version 2.3) ir replece in the pom xml the place holder

for example I have 

```
      <dependencies>
         <dependency>
            <groupId>com.mycompany.myartifact</groupId>
            <artifactId>mayartifact</artifactId>
            <version>${myartifact.version}</version>
          </dependency>
      </dependencies>
```

the result is

```
        <dependency>
            <groupId>com.mycompany.myartifact</groupId>
            <artifactId>mayartifact</artifactId>
            <version>1.0.0-RELEASE</version>  
        </dependency>
```

In previos version that not hapened, the poms keeps theirs placeholder and it was necesary use version:update-properties to do those changes when you have properties placeholders.

Now in usin new version it changes the placeholders and you lose your pom structure usin placeholders properties.

**Comment by erikvanoosten** [comment]
We have the same problem in the artifact id.

**Comment by erikvanoosten** [comment]
This little toy project can be used to play with the problem.
[versions-showcase.zip](https://github.com/mojohaus/versions-maven-plugin/files/619414/versions-showcase.zip)

For example, when you invoke
```
mvn -U org.codehaus.mojo:versions-maven-plugin:2.3:update-parent \
        org.codehaus.mojo:versions-maven-plugin:2.3:use-latest-releases \
        org.codehaus.mojo:versions-maven-plugin:2.3:update-properties \
        org.codehaus.mojo:versions-maven-plugin:2.3:commit
```

inside the project, I expect the dependency to scalatest to be updated. Currently it is not.

**Comment by erikvanoosten** [comment]
We don't have this problem when we invoke the plugin with the following command:

```
mvn -U org.codehaus.mojo:versions-maven-plugin:2.3:update-parent \
        org.codehaus.mojo:versions-maven-plugin:2.3:use-latest-releases \
        org.codehaus.mojo:versions-maven-plugin:2.3:update-properties \
        org.codehaus.mojo:versions-maven-plugin:2.3:commit
```
