### ISSUE TITLE
Respect skip configuration

### ISSUE THREAD

**Issue by foal** [mojohaus/versions-maven-plugin#110]
It will be greate if plugin will respect `skip` option

``` xml
                <configuration>
                    <skip>true</skip>
                </configuration>
```

**Comment by khmarbaise** [comment]
Can you explain a little bit more why you need a skip configuration ? Usually this shows that there is a smell in your build..?

**Comment by foal** [comment]
I do not remember what exactly was a problem, but think it was some issue with version replacing/resolving, not a reporting (e.g. update-parent or resolve-ranges goals).

**Comment by khmarbaise** [comment]
The replacing of versions etc. should be done on command line and not within the pom file...so I'm not sure if a skip would help here...sounds like wrong usage...If you have further information please don't hesitate to reopen the issue..

**Comment by Alexilmarranen** [comment]
I also need this option. This setting is needed to speed up the build of work assemblies. Yes, I understand that the plug-in's work is short, but when there are many such plugins...
