### ISSUE TITLE
For Set mojo add an nextVersion option similar to nextSnapshot

### ISSUE THREAD

**Issue by hackmann** [mojohaus/versions-maven-plugin#115]
We generate an incremental build for every merge and have our CI server run ``mvn -DnewVersion=major.minor.${BUILD_NUMBER} set``. But this requires to update CI job each time there is a change to major or minor versions.

It would be nice if set had an option to automatically increment the last part of the version similar to running:

    mvn -DnextSnapshot=true versions:set
    mvn -DremoveSnaphot=true versions:set

**Comment by khmarbaise** [comment]
After taking a look into this why not using existing plugins like this:
```
mvn build-helper:parse-version versions:set \
     -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.${BUILD_NUMBER}
```
Wouldn't that solve the problem?

**Comment by hackmann** [comment]
Thanks, I didn't know about build-helper:parse-version.
