### ISSUE TITLE
could not resolve when update parent version to snapshot version

### ISSUE THREAD

**Issue by donovankim** [mojohaus/versions-maven-plugin#121]
there is 0.1.2-SNAPSHOT, is latest version.
I've tried as below.
mvn versions:update-parent -DallowSnapshots=true -N -DparentVersion=(0.1.1,0.1.2]
mvn versions:update-parent -DallowSnapshots=true -N -DparentVersion=0.1.2-SNAPSHOT
mvn versions:update-parent -DallowSnapshots=true -N -DparentVersion=[0.1.2-SNAPSHOT]
mvn versions:update-parent -DallowSnapshots=true -N -DparentVersion=[0.1.2-SNAPSHOT,)
mvn versions:update-parent -DallowSnapshots=true -DparentVersion=(0.1.1,0.1.2]
mvn versions:update-parent -DallowSnapshots=true -DparentVersion=0.1.2-SNAPSHOT
mvn versions:update-parent -DallowSnapshots=true -DparentVersion=[0.1.2-SNAPSHOT]
mvn versions:update-parent -DallowSnapshots=true -DparentVersion=[0.1.2-SNAPSHOT,)
...
[WARNING] Not updating version: could not resolve any versions

it does not work.

**Comment by donovankim** [comment]
my maven version is

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_20, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_20/jre
Default locale: ko_KR, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-431.1.2.0.1.el6.x86_64", arch: "amd64", family: "unix"

and plugin version is 2.3.

**Comment by philipebogdan** [comment]
Have you resolved this issue, or still facing this problem?
I you found a solution for this, please share it.

Thanks,
Bogdan

**Comment by idij** [comment]
Try with `-DallowSnapshots=true` on the command line. I know it's not documented for that command, but this allows it to work for me when updating to a SNAPSHOT.

**Comment by khmarbaise** [comment]
The `allowSnapshots` is documented for the goal [update-parent ](http://www.mojohaus.org/versions-maven-plugin/update-parent-mojo.html).

**Comment by khmarbaise** [comment]
The questions is: Which version does the parent currently have?...I have tested it like this:

```xml
  <parent>
    <groupId>com.soebes.smpp</groupId>
    <artifactId>smpp</artifactId>
    <version>2.3.0</version>
  </parent>
  <groupId>thing</groupId>
  <artifactId>thing</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
```
Using: `mvn versions:update-parent` where currently a version `2.3.1-SNAPSHOT` exists...which will not being updated.

But if I change my call to `mvn versions:update-parent -DallowSnapshots=true`  it will be updated to `2.3.1-SNAPSHOT` in the parent. 
This has been tested with versions-maven-plugin 2.3 and I have tested also with the current master of the code...which behaves exactly the same...Furthermore If I extends my call like this:
```
mvn versions:update-parent -DallowSnapshots=true -DparentVersion=2.4.0-SNAPSHOT
```
which will result in updating to version `2.3.1-SNAPSHOT`.

Furthermore the message given in the question:
```
[WARNING] Not updating version: could not resolve any versions
```
will give me the hint that the given versions (newer SNAPSHOT's etc.) do not really exist....

Unfortunately I don't see any issue here...So I close this issue...If you have further details please don't hesitate to reopen the issue....
