### ISSUE TITLE
I don't think 'mvn versions:update-properties' cannot process properties in parent pom

### ISSUE THREAD

**Issue by ph-hs** [mojohaus/versions-maven-plugin#122]
foo-parent:
   <jetty.version>9.1</jetty.version>

foo-child
   parent-pom: foo-parent
   deps
      dep
         <group>org.eclipse.jetty</group>
         <artifactId>jetty-server</artifactId>
         <version>${jetty.version}</version>

.. if run through 'mvn versions:update-properties' it doesn't flag the jetty dep as having releases after 9.1, but should.

**Comment by PeterWippermann** [comment]
I see you edited the title of your issue and changed it's meaning to the contrary. Was this intended?

I just noticed that the resolution and analysis of properties (used for version information) in parent POMs does not work. Do you agree?

**Comment by darrenyeats** [comment]
See my related answer here: http://stackoverflow.com/questions/25034556/how-can-i-update-a-property-in-a-maven-pom/43280162#43280162.

**Comment by paul-hammant** [comment]
Yup, I'm definitely double-negativing there.

**Comment by paul-hammant** [comment]
@darrenyeats - I read your S.O. answer. Forgive me, but I can't work out your suggested remedy is for projects structuring trying to centralize version props to a single place ... for example http://github.com/jooby-project/jooby does that.

**Comment by khmarbaise** [comment]
To handle such thing correctly you should use dependencyManagement in parent pom and in child pom's only simply dependency without any version which is handled by the dependencyManagement in parent at a single location.
