### ISSUE TITLE
Update-properties updates to latest dependency from repository not specified

### ISSUE THREAD

**Issue by midikem** [mojohaus/versions-maven-plugin#127]
Update-properties updates to latest dependency from repository not specified

[INFO] --- versions-maven-plugin:2.3:update-properties (default-cli) @ bla-project ---
[INFO] artifact se.something.commons:commons: checking for updates from development
[INFO] artifact se.something.commons:commons: checking for updates from external
[INFO] Updated ${commons.version} from 5.0.6622 to 5.0.6626

The version called 5.0.6626 is not in repository development or external. Its in a repository called release. And i don't want that version at the moment. I want the latest from development.

**Comment by khmarbaise** [comment]
So you mean you would like to have a SNAPSHOT ? Correct? Currently there is no option to make separation between repositories...The differences between developer (SNAPSHOT) and releases are simply not ending with `-SNAPSHOT`?

**Comment by midikem** [comment]
No I don't want a SNAPSHOT version! The output say correctly its looking in development and external! But the version it updates to is from another repository not specified in the output. So it looks in other repositories not specified!

**Comment by khmarbaise** [comment]
At the moment there is no option etc. to control from which repository a dependency is resolved...Apart from that to me it looks like a problem that you seemed to be having two repositories which contain artifacts with the same groupId/artifactId/... which is in general not a good idea. 
The repository might be not in the output if it's not explicitly requested separately. This version could already been on the local cache ...?Furthermore in such situation a debugging output via `mvn -X ...` could help...

**Comment by midikem** [comment]
Well if update properties say it looks in two repositories but resolves stuff from other repositories not listed in the output! That means who ever can make a artifact that will be resolved instead of the stuff that should be. Because its looking basically in all repositories that exist! So basiclly if you are unlucky and somebody have an artifact with the same name as yours then it will be resolved.

**Comment by khmarbaise** [comment]
I didn't wrote from repository. I wrote from `local cache` which is something wrong. Apart from that it will be true as you mentioned. GroupId/ArtifactId must be unique...to identify exactly one artifact (plus version)...

**Comment by midikem** [comment]
Well as it is now its kind of confusing that it getting stuff from repositories not listed. Its imposible to debug where stuff is comming from then.

**Comment by khmarbaise** [comment]
Can you make a run with `-X` and send me the output maybe privately if you don't like to post here in public....otherwise I can't help ...cause it looks like something wrong in your setup...using two repositories which contains the same artifact using the same coordinates...and not to forget the local cache (~/.m2/repository)....

**Comment by midikem** [comment]
I will try to reproduce it again when I have time. You might be right that
I had forgot the local repository. Thats easy to forgot.

Regards
Anders

Den 15 juni 2017 16:03 skrev "Karl Heinz Marbaise" <notifications@github.com

**Comment by ypk4** [comment]
> At the moment there is no option etc. to control from which repository a dependency is resolved...Apart from that to me it looks like a problem that you seemed to be having two repositories which contain artifacts with the same groupId/artifactId/... which is in general not a good idea.
> The repository might be not in the output if it's not explicitly requested separately. This version could already been on the local cache ...?Furthermore in such situation a debugging output via `mvn -X ...` could help...

Is there now an option to control from which repository a dependency is resolved in latest 2.7 version?
