### ISSUE TITLE
Introduce a switch if imported dependencies should also be analysed

### ISSUE THREAD

**Issue by PeterWippermann** [mojohaus/versions-maven-plugin#129]
In my application I use Spring Boot. Thus I set up the Dependency Management as follows:
```xml
        <dependencyManagement>
          <dependencies>
            <!-- Spring Cloud Dependencies -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
Sprint Boot will manage my dependencies for me and guarantees that the selected versions work well together.
That's why I'd like to **exclude the dependencies that are imported** by Spring Boot from the [versions:dependency-updates-report](http://www.mojohaus.org/versions-maven-plugin/dependency-updates-report-mojo.html) report. Otherwise I get suggested updates in my report that are out of scope for me.

I think it would be great to introduce a new boolean parameter to toogle if those imported dependencies should also be analysed. To stay backwards compatible it would default to `true`.

Don't get me wrong: I still want the importing dependency to be analysed, but not the dependencies it imports. That way I would still get notified if there's a newer version of Spring Boot / Dependencies.

**Comment by cs01lg** [comment]
I think this has already been raised in #46

**Comment by PeterWippermann** [comment]
It depends, I still want `<dependencyManagement>` to be processed so I get notified about outdated versions. However, I don't want to be informed about transitive and/or imported dependencies.

In #46 the OP asked to totally disable processing of dep-mgmt on request.

**Comment by khmarbaise** [comment]
Currently the result of this looks like this:
![image](https://user-images.githubusercontent.com/42484/27255822-73cd5d7e-53a6-11e7-91a6-db21e7d4bb6e.png)
What do you think?

**Comment by PeterWippermann** [comment]
Hi @khmarbaise ,
your solution looks great to me! Thanks for incorporating this feature and mainting this project :-)
On my behalf, sorry for the late feedback...

I'd be very happy to use it in my current setup! Is there a chance for a 2.5 release in the near future? I saw you usually [release once a year or less](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.mojo%22%20AND%20a%3A%22versions-maven-plugin%22).
