### ISSUE TITLE
can't set version on sub-module that has external parent

### ISSUE THREAD

**Issue by KostyaSha** [mojohaus/versions-maven-plugin#13]
Hi, i read documentation but still see no description how parent is related for versions:set.

I have a project that has root pom and submodules, but one of submodules uses external (non-project) parent. When i'm setting version such sub-module is ignored. I tried to specify `-DgroupId=my.group` (not inherited from external project) that is the same for all sub-modules, but it doesn't work.

**Comment by khmarbaise** [comment]
This could be tried with the following:
```
mvn versions:set -DgroupId=* -DartifactId=module-a* -DoldVersion=* -DnewVersion=2.0.9-SNAPSHOT -DupdateMatchingVersions=false
```
If you have a example project that would be great so I can check against the current code...Apart from that I will close the issue for now. If you have further detailed information please don't hesitate to reopen the issue.
