### ISSUE TITLE
How to change the version that multi-module with dependency

### ISSUE THREAD

**Issue by ascrutae** [mojohaus/versions-maven-plugin#130]
Hi

Here is my project struct :
A (the parent project)
--B
--C

but project B is dependency to Project C, I cannot change the dependency version in the pom.xml of  project B when I use the command `mvn versions:update-child-modules -DgenerateBackupPoms=false ` .

Could you give me some advise to solve this problem?

Thanks

**Comment by khmarbaise** [comment]
Maybe I misunderstand a thing here. But why not simply using:
```
mvn versions:set -DnewVersion=1.2.3
```
