### ISSUE TITLE
Final Move to Maven 3+ Only

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/versions-maven-plugin#139]
* Change Maven Version 3.0 minimum
* Updated dependencies
* Using maven-artifact-transfer 0.9.0
* Replace old code with generics code.

**Comment by khmarbaise** [comment]
Keep as long as possible the branch issue-139-maven-3.0-only to be able to make a 2.4 release in between if needed.

**Comment by epabst** [comment]
@khmarbaise I'd really like to build onto this branch for #270, however, it doesn't compile.

**Comment by famod** [comment]
After https://issues.apache.org/jira/browse/MNG-6799, the move to Maven 3+ would probably _also_ fix the problem of `display-plugin-updates` hanging in `StringSearchModelInterpolator` in certain situations/projects (e.g. https://github.com/vackosar/gitflow-incremental-builder).
