### ISSUE TITLE
display-plugin-updates goal relies upon deprecated project prerequisites maven version

### ISSUE THREAD

**Issue by mkotelba** [mojohaus/versions-maven-plugin#146]
The use of the project/prerequisites/maven POM XML element has been deprecated for ~all of Maven v3.x. As of Maven v3.5.0, using the element in non Maven plugin projects results in an (annoying) explicit warning (see [MNG-6092](https://issues.apache.org/jira/browse/MNG-6092)).

The current/correct behavior is to use the [requireMavenVersion Maven Enforcer plugin rule configuration](https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html).

I would humbly ask that this fix be part of the [3.0.0 Milestone](https://github.com/mojohaus/versions-maven-plugin/milestone/2), if at all possible.

**Comment by khmarbaise** [comment]
See #96
