### ISSUE TITLE
versions:display-dependency-updates reports updates for projects within reactor

### ISSUE THREAD

**Issue by cstamas** [mojohaus/versions-maven-plugin#151]
For example, if you work on a branch of a project (call it 1.x), that has master with 2.x along with releases in Central, the mojo will report for _all reactor modules_ (more precisely, for a reactor module depending on other reactor module, inter-build dependency) that there is 2.x update available 😄 

Which is wrong. Projects present in reactor should not be checked for "newer" version IMHO.

**Comment by khmarbaise** [comment]
Hi @cstamas have you used version 2.3 of versions-maven-plugin? My first IT does not show any issue? Do you have more details ?
