### ISSUE TITLE
Allow versions:set to be called with selected projects -pl

### ISSUE THREAD

**Issue by atiyou** [mojohaus/versions-maven-plugin#152]
I tried using a version plugin with the --pl option (to specify a list of modules to process)
- pom.xml (pom parent) - core / pom.xml (module1 pom) - app / pom.xml where the application depends on -> base module
Command: mvn -pl core, build-helper application: parse-version version: set -newVersion = \ $ {parsedVersion.majorVersion}. \ $ {ParsedVersion.minorVersion}. \ $ {ParsedVersion.nextIncrementalVersion} -SNAPSHOT

But it simply modifies the basic module! (And of course the dependency section in the application module)
The parse-version goal is called twice as expected, but the "versions:set" for app module is not performed
I think the versions: set can only handle a single module or all modules of the aggregator. Am i right?

**Comment by khmarbaise** [comment]
See #139 cause currently versions-maven-plugin is based on Maven 2 and reading the pom's itself instead of the correct handling for reactor information (-pl option) which means that does not work at the moment..

**Comment by atiyou** [comment]
any idea about when it will be released ?
i have tried using branch maven3-only got the same result

**Comment by khmarbaise** [comment]
The maven3-only branch is only the beginning of the migration to Maven 3 only...so it's only scratching the surface...it will take time...

**Comment by mmoossen** [comment]
any recommended workaround?
