### ISSUE TITLE
resolve-ranges doesn't resolve version ranges in parent elements

### ISSUE THREAD

**Issue by stephenwiebe** [mojohaus/versions-maven-plugin#16]
Version ranges for parent elements were added in [Maven 3.2.2](https://maven.apache.org/docs/3.2.2/release-notes.html), but the 'versions:resolve-ranges' goal doesn't handle them at all. 'versions:update-parent' also doesn't do anything, and in fact it prints:

[INFO] Project does not have a parent

which is obviously incorrect. I'm not sure what the correct behavior should be when 'versions:update-parent' is called when a version range is used, but 'versions:resolve-ranges' should definitely support resolving version ranges in parent elements.

**Comment by stephenwiebe** [comment]
I wish this was an easy enough fix that I could make myself, but it looks like the versions plugin needs to be heavily modified to eliminate the reliance on deprecated and old Maven 2.x libraries. I don't suppose there are any plans to do that?

**Comment by lorijoan** [comment]
+1 to this...I am seeing the same issue with regards to versions:resolve-ranges.  It's a big headache that needed a strange (and sometimes potentially unreliable) workaround involving which in fact involves versions:update-parent.  I have not found versions:update-parent to be broken.

**Comment by ouaibsky** [comment]
+1. It really make sens to have it in parent
I prefer to have fix version of dependencies defines in a parent pom, then putting a version range in parent section is more manageable.

**Comment by rohshall** [comment]
+1, we have a parent maven template that we update for minor dependencies' changes and we have to update all dependent projects' POM for this trivial change. So, this feature is important to us.

**Comment by mbamber** [comment]
+1, we have a parent pom that contains a collection of dependency versions. When any of these versions is updated, we have to update the parent pom in all 72 of our projects. This would be much better if `mvn versions:resolve-ranges -DprocessParent` would resolve these ranges; maybe I am missunderstanding what this goal does?

**Comment by grandon** [comment]
+1 we are facing the same issue.

**Comment by ThYpHo0n** [comment]
Thanks for the fix, we ran into the same error and this one fixes it.
Just as a side note, mvn versions:update-parent still doesn't resolve the parent version if you use version ranges.

**Comment by ryenus** [comment]
For those wondering why `mvn versions:resolve-ranges` doesn't work, even though the feature is clearly implemented, please make sure to use `2.4` or later versions, and set `processParent` to **true**, e.g.:

    mvn -X org.codehaus.mojo:versions-maven-plugin:2.8.1:resolve-ranges -DprocessParent=true

Then the parent pom version can be updated as one would expect.
