### ISSUE TITLE
Support updating properties for the series of use-xxx goals

### ISSUE THREAD

**Issue by xjj59307** [mojohaus/versions-maven-plugin#163]
The series of use-xxx goals as follows couldn't handle property updates. Or is there any goal I am missing?
 
versions:use-releases
versions:use-next-releases
versions:use-latest-releases
versions:use-next-snapshots
versions:use-latest-snapshots
versions:use-next-versions
versions:use-latest-versions

**Comment by khmarbaise** [comment]
This is why update-property, update-properties exist. See the documentation http://www.mojohaus.org/versions-maven-plugin/

**Comment by xjj59307** [comment]
Thank you for the reply.
Since we are maintaining multiple versions of our project. We couldn't perform use-releases for the properties using update-properties because it will always update all properties to the latest release version. I found three new parameters -allowxxx were just released today that we exactly wanted!

**Comment by khmarbaise** [comment]
The release not yet out...the vote is running...at least on monday it will be available in Maven Central...
