### ISSUE TITLE
update-property/update-properties goal: Emit a warning for non existing properties 

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/versions-maven-plugin#171]
It should be checked to give a warning about not existing properties for the update-property and update-properties goals.

**Comment by sellersj** [comment]
I've run into this problem for a multi-module project when the property is only in the top level pom. It fails on the first child module.

**Comment by sellersj** [comment]
For me, if you want to only run on the top level then that can be done with the `--non-recursive` maven flag.
