### ISSUE TITLE
set goal fails with NPE if project artifactId contains property

### ISSUE THREAD

**Issue by aleksandr-m** [mojohaus/versions-maven-plugin#172]
Similar to the #76 and #85 but property is used in project `artifactId` not in dependency.

https://github.com/aleksandr-m/mcve-set-property

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>mcve-set-property-${some.prop}</artifactId>
    <packaging>jar</packaging>
    <name>mcve-set-property</name>
    <version>0.0.1</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <some.prop>testing</some.prop>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.4</version>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by khmarbaise** [comment]
You know that Maven itself already shows warnings in your build about the property in groupId/artifactId?

**Comment by aleksandr-m** [comment]
@khmarbaise Hmm... interesting. Now when you've mentioned I remember reading some discussion about it (maybe this one [MNG-4715](https://issues.apache.org/jira/browse/MNG-4715)).

Feel free to close this issue if you think it is not feasible to support this.

**Comment by khmarbaise** [comment]
The discussion about the property for a version is something completely different and works in Maven 3.5.0 (see [Release Notes](http://maven.apache.org/docs/3.5.0/release-notes.html)). 

There two things:
1. prevent the NPE which shouldn't be coming up
2. Support such thing

The first thing must be fixed. About the second step I'm thinking about...
