### ISSUE TITLE
versions plugin ignores enforcer rules

### ISSUE THREAD

**Issue by mlgiroux** [mojohaus/versions-maven-plugin#181]
I'm running the versions plugin on my POM as follows:
mvn org.codehaus.mojo:versions-maven-plugin:2.4:display-plugin-updates

The versions plugin to complains that maven version has not been specified:
[ERROR] Project does not define required minimum version of Maven.
[ERROR] Update the pom.xml to contain maven-enforcer-plugin to
[ERROR] force the maven version which is needed to build this project.
[ERROR] See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[ERROR] Using the minimum version of Maven: 3.0.5

Starting with maven 3, the <prerequisites> element is no longer used, and the maven version is specified by maven-enforcer-plugin rules.  My POM does not contain prerequisite, and does contain the requireMavenVersion rule, and the enforcer goal is bound to pre-cleane and validate rules.

The maven-enforcer-plugin is configured as follows which works as desired for clean and builds:
`         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-enforcer-plugin</artifactId>

            <configuration>
               <rules>
                  <requireJavaVersion>
                     
                     <version>1.8</version>
                  </requireJavaVersion>

                  <requireMavenVersion>
                     
                     <version>3.2.5</version>
                  </requireMavenVersion>

                  <requireProperty>
                     <property>java.home</property>
                     <message>You must set the JAVA_HOME environment variable.</message>
                  </requireProperty>
               </rules>
            </configuration>

            <executions>
               <execution>
                  <id>enforce-clean</id>
                  <goals>
                     <goal>enforce</goal>
                  </goals>
                  <phase>pre-clean</phase>
               </execution>
               <execution>
                  <goals>
                     <goal>enforce</goal>
                  </goals>
                  <phase>validate</phase>
               </execution>
            </executions>
         </plugin>
`

**Comment by khmarbaise** [comment]
See #48
