### ISSUE TITLE
Update <scm><tag>...</tag></scm>

### ISSUE THREAD

**Issue by anton-johansson** [mojohaus/versions-maven-plugin#182]
I've been using `versions:set` for a long time, and I'm moving away from the `maven-release-plugin` all together. I'm just missing one thing when using `versions:set`. I want to be able to update the `<scm><tag></tag></scm>` entry in my POM.

It would be awesome if I could do this through `versions:set` or another goal in the `versions` plugin.

Any plans to add something like this? Or is this functionality available somewhere else, that I have missed?

**Comment by khmarbaise** [comment]
At the moment I don't see this as a functionality which would be added but on the other hand why not...What about offering a pull request ? But it's not that trivial to do such things...

**Comment by anton-johansson** [comment]
Sure, I could give it a shot, when I have time.

Would you prefer a separate goal (i. e. `versions:set-scm-tag`) or a parameter to `versions:set` (i. e. `mvn versions:set -DnewVersion=1.0.0 -DscmTag=v1.0.0`)?

**Comment by anton-johansson** [comment]
Decided to go for a separate goal, for simplicity. See #184.

**Comment by khmarbaise** [comment]
Hi, first thanks for your contribution and yes please add the information to the ReleaseNotes as well...apart from that If I correctly see the code this will only change the `<scm><tag>..</tag></scm>` information which is from my point of view not enough. It should also update the developerConnection and the connection as well. Otherwise you can pick the pom file and from there you can checkout the code from the correct location....

**Comment by anton-johansson** [comment]
I've updated the release notes.

I'm not sure what you mean. Why would the `developerConnection` or `connection` be updated? Those are the same for any tag.

Compare this to the `maven-release-plugin`. It updates the version and the SCM tag and commits that before actually tagging. I would like an efficient way of doing the same, but without using the `maven-release-plugin`.

Here's what I would like to achieve for my release-flow:

```shell
$ git checkout [commitSHA]
$ mvn versions:set versions:set-scm-tag -DnewVersion=1.0.0 -DnewTag=v1.0.0 -DgenerateBackupPoms=false
$ git add .
$ git commit -m "Set release 1.0.0"
$ git tag v1.0.0
$ git push --tags
$ mvn deploy
```

**Comment by khmarbaise** [comment]
In case of Git the [tag in scm is enough](https://github.com/mojohaus/versions-maven-plugin/commit/b8f1df7c723d34bbe62e71024d3d78637ca447c8), but not for Subversion. If you use Subversion this means also the scm/connection and scm/developerConnection needed to be changed according to the tag.
For example take a look [here](https://svn.apache.org/repos/asf/maven/plugins/tags/maven-clean-plugin-3.0.0/pom.xml)  which looks like this:
```xml
<scm>
<connection>scm:svn:http://svn.apache.org/repos/asf/maven/plugins/tags/maven-clean-plugin-3.0.0</connection>
<developerConnection>scm:svn:https://svn.apache.org/repos/asf/maven/plugins/tags/maven-clean-plugin-3.0.0</developerConnection>
<url>http://svn.apache.org/viewvc/maven/plugins/tags/maven-clean-plugin-3.0.0</url>
</scm>
```
and maybe for other version controls as well (Mercurial, Bazaar I don't know how it looks like there)...

But for the first step we have to enhance the documentation with a prominent hint about the limitation for Git only...I think that should be feasible for the moment.

**Comment by anton-johansson** [comment]
Ah, okay. That makes sense. However, the goal is currently called `set-scm-tag`, which would obviously only set the tag. Maybe we should consider naming the goal `update-scm`, where `newTag` is one of the parameters. However, for now, I think updating the tag is enough. We can always add additional features when someone needs it. I aren't 100% sure how the connections should be updated for SVN or other systemsin a good way, so that would be better if someone else added.

**Comment by anton-johansson** [comment]
Bump: Where would you want me to document it?
