### ISSUE TITLE
use-latest-releases does not evaluate custom rule set file anymore when allowMajorUpdates=false

### ISSUE THREAD

**Issue by maikebertpsc** [mojohaus/versions-maven-plugin#183]
Since version 2.4 the use-latest-releases mojo is broken regarding the custom rule set file.
It's not taking care when a custom rule set is given.

**Comment by khmarbaise** [comment]
First in the are of the rule set there has no change apart from that it would be very helpful to make test project and your rule set etc. and show how you called versions-maven-plugin and what you have expected...furthermore which Maven versions you use etc. Furthermore a log file would also be helpful...

**Comment by maikebertpsc** [comment]
I looks like the problem is caused by introduction of MajorMinorIncrementalFilter to UseLatestVersionsMojo.
