### ISSUE TITLE
Enable the Versions Plugin to find rules via the classpath

### ISSUE THREAD

**Issue by obfischer** [mojohaus/versions-maven-plugin#193]
It could be usefull to search for rules also on the classpath to ease the use of a single rules set in multiple projects. This would allow a user of the Maven Versions Plugin to distribute its rules set inside a Jar and to integrate in a Maven project by using the standard Maven dependency mechanism.

**Comment by obfischer** [comment]
I will provide an PR for this issue.

**Comment by khmarbaise** [comment]
That would be great...

**Comment by obfischer** [comment]
I am working on a PR including tests and additions to the documentation.

**Comment by khmarbaise** [comment]
Can you please squash the commits....

**Comment by obfischer** [comment]
Yes, will do that before I will create an PR.

**Comment by obfischer** [comment]
I created an PR for this issue.
