### ISSUE TITLE
maven-3.5 deprecates <prerequisites>; use maven-enforcer-plugin instead

### ISSUE THREAD

**Issue by aledell** [mojohaus/versions-maven-plugin#210]
maven 3.5 deprecates the <prerequisites> tag and recommends using maven-enforcer-plugin instead.  versions-maven-plugin currently includes this in its pom.xml:
```
  <prerequisites>
    <maven>3.0</maven>
  </prerequisites>
```
There at least related issues open about this:
* [versions plugin ignores enforcer rules](https://github.com/mojohaus/versions-maven-plugin/issues/181) - duplicate
* [versions:display-plugin-updates does not understand maven-enforcer-plugin](https://github.com/mojohaus/versions-maven-plugin/issues/48)
* [Goal displayPluginUpdates generates incorrect warnings on the <prerequisites> section for non-plugin projects](https://github.com/mojohaus/versions-maven-plugin/issues/56)
* [The fix for #56 is broken](https://github.com/mojohaus/versions-maven-plugin/issues/173)
* [and even a pre-github bug](https://web.archive.org/web/20150514123930/http://jira.codehaus.org/browse/MVERSIONS-272)

In those issues, you will see that #56 updated the output to suggest using maven-enforcer-plugin, and that #173 shows that #56 changed the plugin's advice without changing its implementation.

Several strategies have been suggested already, but I haven't seen anyone suggest an actual implementation that uses maven-enforcer-plugin.  The documented maven-enforcer-plugin usage can be found [here](https://maven.apache.org/enforcer/enforcer-rules/requirePluginVersions.html).

**Comment by aledell** [comment]
issue 195 has good commentary about what should be done.

My pull-request is (at least at this time) incomplete.  At least one method in org.codehaus.mojo.versions.DisplayPluginUpdatesMojo, getRequiredMavenVersion(), still interprets the value from <prerequisites>.

**Comment by rhwood** [comment]
I don't see what this has to do with #195. The use of ```<prerequisite>``` is deprecated only in non-maven-plugin type POMs, and this project is a maven-plugin type POM.
