### ISSUE TITLE
versions:use-latest-versions doesn't set previous releases when allowSnapshot=false

### ISSUE THREAD

**Issue by chetanddesai** [mojohaus/versions-maven-plugin#213]
I have a use-case where I use-latest-versions where I allowSnapshots on my mainline (which works great) but when I set it to try to swap all the snapshots to releases for my release branch using `-DallowSnapshots=false`, it won't "go back in versions" to use the latest release version.

Example:
`pom.xml` has `1.1-20170929132713` but I want to have it update to the latest release candidate which is `1.0`

Is there a way to get this behavior or is it a new feature?

**Comment by DiJu519** [comment]
https://github.com/mojohaus/versions-maven-plugin/issues/78

**Comment by chetanddesai** [comment]
Thanks @DiJu519 - I see`allowDowngrade` in the update-properties documentation, but not yet in use-latest-versions.  http://www.mojohaus.org/versions-maven-plugin/use-latest-versions-mojo.html . Does it work for that as well?

**Comment by DiJu519** [comment]
Last time i was in the code I did not see it implemented.

**Comment by chetanddesai** [comment]
Hopefully it's not too much effort to use the same strategy for some of the other goals.

**Comment by chetanddesai** [comment]
@jdileonardo I think this one is still an issue - I don't see the `allowDowngrade` option, can we reopen it?

**Comment by ajarmoniuk** [comment]
Looking into it.
