### ISSUE TITLE
versions:update-property doesn't look for dependencies in child pom.xml files.

### ISSUE THREAD

**Issue by abhijeettannu** [mojohaus/versions-maven-plugin#217]
If parent pom.xml has property defined without any dependency, but the child pom.xml has the dependency defined, then this plugin is not scanning child pom.xml files and figuring out the correct version. Only when the dependency is added to parent pom, it works.

Example: mvn versions:update-property "-Dproperty=test.version" "-DnewVersion=[1.1,10]"

**Comment by vrevelas** [comment]
Same issue. Also see https://stackoverflow.com/questions/3628471/maven-versions-plugin-not-picking-up-properties-from-parent
