### ISSUE TITLE
Force update in versions:update-properties

### ISSUE THREAD

**Issue by JRaue** [mojohaus/versions-maven-plugin#218]
I am struggling to accomplish using goal versions:update-properties to update a property containing a version to a new version without any checks.

The requirement is that in case that version does not exist, the property shall be updated, and subsequently the build shall fail (instead of silently building with the old version).

I do not see anyway to establish. A property forceUpdate would be helpful. Thanks!

**Comment by niklausxiao** [comment]
I think this is useful for update-property goal, sometimes we use some customized versions.
