### ISSUE TITLE
Use-Releases with allowRangeMatching should be able to narrow the range to build-numbers only

### ISSUE THREAD

**Issue by talksinmath** [mojohaus/versions-maven-plugin#220]
We are using the use-releases mojo with the `allowRangeMatching` option turned on.

We do need the option to pad the version used for range matching so that only applicable build numbers are considered even if minor or incremental versions are omitted.

Example:
When using 1.0-SNAPSHOT as a range match, 1.0.1.1 would match. This behaviour is not always intended.
Another expected result would be that only 1.0.0-1 should match (e.g. when 1.0.0 and 1.0.1 are diverging releases).

I will submit a pull request shortly with an implementation that we are using internally already.
Thanks for your consideration.

**Comment by ajarmoniuk** [comment]
I see this has been hanging unresolved for quite some time. Do you still need the feature?

**Comment by talksinmath** [comment]
Nope. Moved on quite some time ago :)
Thanks for asking, forgout about this.

**Comment by ajarmoniuk** [comment]
@slachiewicz can be closed
