### ISSUE TITLE
display-dependency-updates is showing a version that no longer exists

### ISSUE THREAD

**Issue by efenderbosch** [mojohaus/versions-maven-plugin#234]
A coworker accidentally published an incorrect version "62" instead of "1.2.062". When running display-dependency-updates 62 was showing, so I deleted it from my local ~/.m2/repositories cache and also deleted it from our private Nexus. The build is now fixed and we have versions past 1.2.063. For some reason display-dependency-updates is still showing version 62. I tried deleting ``~/.m2/repository/org/codehaus/mojo/versions-maven-plugin/`` but it still shows up. Is there another cache somewhere that has this info in it? I know that version 62 is gone from Nexus because the build fails if we try to use it.

We could add a ruleset to ignore this version, but I'd prefer not to have to do that in all of our projects since this used in all of them.

**Comment by khmarbaise** [comment]
Have you regenerated the Maven Metadata in Nexus ?

**Comment by efenderbosch** [comment]
Sorry, was on vacation. Will check shortly.

**Comment by efenderbosch** [comment]
I went in to our private repo and the mirrors/groups and clicked "rebuild index" and "invalidate cache" and I'm still getting those versions. Is there something else I can try?

**Comment by khmarbaise** [comment]
Can you check the maven-metadata.xml file which is created from your Nexus? Just a second. There two things. Rebuilding index and Rebuilding metadata...you need to rebuild metadata...

**Comment by efenderbosch** [comment]
I added a rebuild metadata task and ran it. Still getting it. We've been suppressing it w/ a rule, so I guess this isn't that important.
