### ISSUE TITLE
Version constraints break 'use-latest-versions' when property-based versions are present 

### ISSUE THREAD

**Issue by robsykes24** [mojohaus/versions-maven-plugin#243]
# Description:
In version 2.2 of the versions-maven-plugin, the 'use-latest-versions' would ignore versions that were declared as a property. This issue has already been identified by #99 and #109.  However, this change in behavior also introduces another problem documented in this issue where the specification of version constraints ( allowMajorUpdates, DallowMinorUpdates, allowIncrementalUpdates) breaks when a property-based version is encountered.  Ideally it would be beneficial to have the behavior of the 2.2 version restored as it would eliminate this issue and also restore the ability to use a combination of property-based and non-property based versions within a given pom.  The versions could then be managed via the 'update-property' and 'use-latest-versions' goals respectively without conflict.

There may be a relationship to #205 

### Project 'a'
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>a</artifactId>

    <version>1.0.1-0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties> 
</project>
```
### Project 'b'
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>b</artifactId>

    <version>1.0.2-0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>

    <properties>
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <dependency.a.version>1.0.4-SNAPSHOT</dependency.a.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>test</groupId>
                <artifactId>a</artifactId>
                <version>${dependency.a.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>

```
### File Structure:
```
test
├── a
│   └── pom.xml
└── b
    └── pom.xml

```

#### Stage 1.0.1-0-SNAPSHOT and 1.0.2-0-SNAPSHOT versions of project 'a'
```
(cd a; mvn clean install)
(cd a; mvn build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-${parsedVersion.nextBuildNumber}-SNAPSHOT')
(cd a; mvn clean install)
```

#### Build 'b' that depends on version 1.0.1-0-SNAPSHOT of 'a' (verifies build works)
`(cd b; mvn clean install)
`
#### Attempt to bump version to next incremental snapshot buildnumber using specific version of versions-maven-plugin (version > 2.2):
```
(cd b; mvn org.codehaus.mojo:versions-maven-plugin:2.5:use-latest-versions -DgenerateBackupPoms=false -DallowMajorUpdates=false -DallowMinorUpdates=false -DallowIncrementalUpdates=false -DallowSnapshots=true)

```
#### Results with versions-maven-plugin > 2.2:
> [ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.5:use-latest-versions (default-cli) on project b: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.5:use-latest-versions failed: Invalid segment, 2, for the 1 segment version: '${dependency.a.version}' -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> 

#### Attempt to bump version to next incremental snapshot buildnumber using specific version of versions-maven-plugin (version = 2.2):
```
(cd b; mvn org.codehaus.mojo:versions-maven-plugin:2.2:use-latest-versions -DgenerateBackupPoms=false -DallowMajorUpdates=false -DallowMinorUpdates=false -DallowIncrementalUpdates=false -DallowSnapshots=true)

```
#### Results with versions-maven-plugin = 2.2:
> Nothing changes since the version is declared as a property

#### Attempt to bump version without constraints using specific version of versions-maven-plugin:
```
(cd b; mvn org.codehaus.mojo:versions-maven-plugin:2.5:use-latest-versions -DgenerateBackupPoms=false -DallowSnapshots=true)

```
#### Results with versions-maven-plugin > 2.2:

> The property is replaced with the new version

```
git diff b/pom.xml
diff --git a/b/pom.xml b/b/pom.xml
index f893352..318627f 100644
--- a/b/pom.xml
+++ b/b/pom.xml
@@ -19,7 +19,7 @@
             <dependency>
                 <groupId>test</groupId>
                 <artifactId>a</artifactId>
-                <version>${dependency.a.version}</version>
+                <version>1.0.1-1-SNAPSHOT</version>
             </dependency>
         </dependencies>
     </dependencyManagement>

```
#### Results with versions-maven-plugin = 2.2:

> Nothing changes since the version is declared as a property

**Comment by ajarmoniuk** [comment]
Looks like the old behaviour has been reverted by #340. Can be closed @slachiewicz
