### ISSUE TITLE
Version updates ignore import scoped BOM dependencies

### ISSUE THREAD

**Issue by drekbour** [mojohaus/versions-maven-plugin#25]
Version 2.2

As per http://stackoverflow.com/questions/7609876/how-to-make-maven-versionsuse-latest-versions-step-up-import-scoped-entry-in-de

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>se.company.maven</groupId>
            <artifactId>maven-third-party-dependencies</artifactId>
            <version>0.0.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
When we run mvn versions:use-latest-versions all our dependencies (and other entries in dependencyManagement) get stepped up except this one.

**Comment by tavin** [comment]
see pull request above -- we've been using my patch for 3+ months with no problems
