### ISSUE TITLE
Property version updates don't work across parent hierarchies

### ISSUE THREAD

**Issue by drekbour** [mojohaus/versions-maven-plugin#26]
Version 2.2

Parent POM has

``` xml
<properties>
  <bom>LATEST</bom>
</properties>

<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>se.company.maven</groupId>
      <artifactId>bom</artifactId>
      <version>${bom}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  <dependencies>
<dependencyManagement>
```

Child POM has

``` xml
<properties>
  <bom>LATEST</bom>
</properties>
```

The child `$bom` property is active (i.e. does control the version of `bom` in use) however `update-properties` and `update-property` do not update `$bom` to latest version. They _will_ do this if the dependencyManagement section exists in the child pom.

Ps. The issue is not specific to the import-scope but is much more easily worked around (by overriding the whole dependency instead of the property).

**Comment by khmarbaise** [comment]
Based on fixed #85 this should be fixed also.
