### ISSUE TITLE
Is 2.6-SNAPSHOT version available in a public repository?

### ISSUE THREAD

**Issue by itelleria** [mojohaus/versions-maven-plugin#266]
Hi, 
I need to use the 2.6-SNAPSHOT version of versions-maven-plugin but I haven't found it in this repository: https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/mojo/versions-maven-plugin/ . The last SNAPSHOT version available is [2.5-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/mojo/versions-maven-plugin/). 

I wonder if 2.6-SNAPSHOT is public in another repository. Otherwise, I'm going to install it in my local repo from the source. 

Thanks.

**Comment by khmarbaise** [comment]
Hi,

now available from here:
https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/mojo/versions-maven-plugin/

**Comment by itelleria** [comment]
Great! Thank you very much!
