### ISSUE TITLE
display-dependency-updates doesn't manage transitive dependencies

### ISSUE THREAD

**Issue by ghusta** [mojohaus/versions-maven-plugin#267]
Only the direct dependencies are managed in this goal. The transitive ones are not.

#### For example : 
When running `mvn versions:display-dependency-updates` on a project with the direct dependency `org.apache.struts:struts-core:1.3.10`, `commons-beanutils:commons-beanutils` (transitive) is not reported whereas there is a newer version than 1.8.0 (latest is 1.9.3).

#### Enhancement : 
Maybe a parameter like `processTransitiveDependencies` could be useful (default false for backward compatibility).

**Comment by ghusta** [comment]
A good starting point could be to use `org.apache.maven.shared.artifact.filter.collection.ProjectTransitivityFilter` in `org.apache.maven.shared:maven-common-artifact-filters:3.0.1`.

Like in : https://github.com/apache/maven-dependency-plugin/blob/maven-dependency-plugin-3.1.0/src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java#L285

**Comment by hemanthacharya** [comment]
Yes, this would very useful.

**Comment by dlakatos847** [comment]
There is a parameter `processDependencyManagementTransitive` which is `true` by default in version `2.7`. It does evaluate transitive depencencies. I think this issue should be closed.

**Comment by ghusta** [comment]
The parameter `processDependencyManagementTransitive` belongs to the goal `dependency-updates-report`.
It's not present in `display-dependency-updates`.

There's also a mention of this parameter here : #291, still unresolved

**Comment by apoorva-sriv** [comment]
This issue should be closed now since transitive dependencies are being reported now, and parameter [`processDependencyManagementTransitive`](https://www.mojohaus.org/versions-maven-plugin/display-dependency-updates-mojo.html#processDependencyManagementTransitive) has been added since `2.11`.
