### ISSUE TITLE
Enhancement: Add -DallowVersionConflicts=true option to update-properties (and possibly use-latest-versions)

### ISSUE THREAD

**Issue by epabst** [mojohaus/versions-maven-plugin#270]
The [Continuous Delivery book by Jez Humble](https://www.amazon.com/Continuous-Delivery-Deployment-Automation-Addison-Wesley/dp/0321601912) proposes a really cool algorithm on page 365 that could be added to the versions plugin.  The algorithm basically follows that rule that updating a version should NEVER introduce a version conflict.  So if project C depends on B and A, and B also depends on A, when there is a new version of A, C won't update to the new A unless there's also a version of B built with that same version of A.  This could be implemented in the update-properties goal with an "allowVersionConflicts=false" option.  The value of this would be awesome because it would prevent binary incompatibilities from being accepted, which significantly reduces the risk when accepting new versions.  Anytime a version won't be accepted because of this rule, the goal should output a warning indicating that there is no version of B with the latest version of A.  The warning would make it very easy to know what the next step is to getting the latest A into the current project.

**Comment by Stephan202** [comment]
CC @dependabot / @greysteil; could be interesting for you guys.

**Comment by greysteil** [comment]
Interesting. I'm really keen to do some kind of resolvability check during Dependabot's Maven updates - it's the one things that's blocking me taking it out of beta.
