### ISSUE TITLE
display-dependency-updates - filter and output width

### ISSUE THREAD

**Issue by connorsadlervelo** [mojohaus/versions-maven-plugin#275]
Hi,

Couple of questions/issues with display-dependency-updates

1. Can we filter by (say) groupId? So only our organization's dependencies are checked
2. The width of outdated-dependencies.txt seems to be fixed at 80 columns. Can this be customized?

Thanks!

**Comment by thomasvamos** [comment]
The output width is hardcoded in [DisplayDependencyUpdatesMojo.java](https://github.com/mojohaus/versions-maven-plugin/blob/28134b4e2a34c5f9ad5d038ba04aab59710e56d3/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java#L68). A switch would be useful :)

**Comment by ajarmoniuk** [comment]
> Can we filter by (say) groupId? So only our organization's dependencies are checked

Implemented in #369 -- will be out in today's release (2.12.0)

> The width of outdated-dependencies.txt seems to be fixed at 80 columns. Can this be customized?

Yes, since version 2.10.0, see `outputLineWidth`

**Comment by ajarmoniuk** [comment]
@slachiewicz I think this ticket could be closed. There seems to be a off-by-1 bug there (the actual line size is 1 character less than requested, but I'll tackle this in another PR).
