### ISSUE TITLE
update-properties goal replaces brackets

### ISSUE THREAD

**Issue by fmarot** [mojohaus/versions-maven-plugin#277]
This issue is kinda the same as #104 which was closed (because I think the creator did not responded) but I'll try to explain differently:

Imagine a pom like this one:

```
<properties>
    <wrapper.version>[1.0.0-SNAPSHOT]</wrapper.version>
</properties>

<dependency>
    <groupId>com.oleamedical.sdk</groupId>
    <artifactId>wrapper</artifactId>
    <version>${wrapper.version}</version>
</dependency>

<dependency>
    <groupId>com.oleamedical.sdk</groupId>
    <artifactId>wrapper-api</artifactId>
    <version>${wrapper.version}</version>
</dependency>
```

If I run "mvn versions:update-properties" then it will update the value inside <wrapper.version></wrapper.version> BUT it will also replace the 2 brackets ! Which means that in a few month if this library has evolved and I run again the versions:update-properties goal, then nothing will be updated as this plugin seems to require the presence of the brackets to replace the value.

So there are two problems from my point of view;
1- why the need for brackets ? Shouldn't this plugin update the properties whatever the value ?
2- if brackets are present in the definition of the property, they should not be replaced (because similarly, bracket are not replaced when they are present in the "dependency" declaration as opposed to the "property" declaration).

I may have missed something please tell me ;)
Regards

**Comment by glianeric** [comment]
Hi,

  I make extensive use of this goal and it works correctly.   Could you give a detailed scenario of what command you are running and how the versions are turning over?

**Comment by fmarot** [comment]
Hello, I tried 2 hours at work and it was working strangely as stated. I tried 5 minutes at home with a hand-made pom and everything was OK ! I'll test again at work and tried to make a Short, Self Contained, Correct Example.

**Comment by ajarmoniuk** [comment]
Looks like an instance of the [XY problem](https://en.wikipedia.org/wiki/XY_problem).

> Which means that in a few month if this library has evolved and I run again the versions:update-properties goal, then nothing will be updated as this plugin seems to require the presence of the brackets to replace the value.

should have been the issue reported. But that is not the case, at least: we have plenty of integration tests which test against this very case: the plugin certainly does *not* require square brackets to replace values.

Regarding the case reported: a version inside square brackets is a range consisting only of the version. The plugin will resolve that range to a newer version, if such is found.

**Comment by ajarmoniuk** [comment]
I think we could perhaps close this unless the OP provides test case for

> Which means that in a few month if this library has evolved and I run again the versions:update-properties goal, then nothing will be updated as this plugin seems to require the presence of the brackets to replace the value.

@slachiewicz
