### ISSUE TITLE
Support multiple properties in 'set-property'

### ISSUE THREAD

**Issue by Dennis-Koch** [mojohaus/versions-maven-plugin#278]
Current only a single property is supported by the SetPropertyMojo. In cases where you have multiple distinct properties which shall be assigned the same "newVersion" you can't do this via plain command line any more.

In my company we currently exactly this problem on the command line:

`mvn versions:set versions:set-property versions:update-child-modules org.eclipse.tycho:tycho-versions-plugin:update-eclipse-metadata -DnewVersion=%NEW_VERSION% -Dproperty=myProperty1,myProperty2 -DgenerateBackupPoms=false -DprocessAllModules -Dtycho.mode=maven`

For different reasons we MUST execute all these mojos - including tycho versioning - in one call to one multi-module build. But the parameter "myProperty1,myProperty2" is interpreted as a single parameter even though it is in the pom.xml impossible to have a "comma" within a key/value property declaration.

I have uploaded a fixed version of the [SetPropertyMojo](https://gist.github.com/Dennis-Koch/c6daeb2e3bec6e31579c8a7cfd89dd15) because I was for whatever reason not able to create a PR

**Comment by easterwood** [comment]
I'm not sure if I understand your issue in the right way but the documentation of goal _set-property_ says it is possible to "...specify multiple property names separated by "," which are all set to the same new version."

**Comment by ajarmoniuk** [comment]
I think this has been resolved by #546

**Comment by ajarmoniuk** [comment]
It's verified to be resolved by that PR, there's even an it testing this very feature.

**Comment by indrakumaryadav** [comment]
is there any option to set multiple versions for multiple properties?
