### ISSUE TITLE
Use latest snapshots ignoring snapshots?

### ISSUE THREAD

**Issue by gigs2go** [mojohaus/versions-maven-plugin#286]
https://github.com/mojohaus/versions-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java#L149

Should not negate the test.

Sorry, I don't have experience in updating github at this level.
I have built and run the plugin locally, and it works better this way :-)

**Comment by gigs2go** [comment]
... and UseNextSnapshots#L133(?)

**Comment by ajarmoniuk** [comment]
@slachiewicz I suggest this bug report be closed (it's kind of stale anyway) unless OP comes up with a meaningful description of the problem and steps to reproduce.
