### ISSUE TITLE
use-next-releases does not respect `processParent` setting

### ISSUE THREAD

**Issue by adamvoss** [mojohaus/versions-maven-plugin#288]
[use-next-releases is documented to have a `processParent` setting](https://www.mojohaus.org/versions-maven-plugin/use-next-releases-mojo.html#processParent).  However, setting the setting to true does not update the parent pom.

A look at the code confirms the Mojo never accesses the `processParent` setting.

**Comment by ajarmoniuk** [comment]
Perhaps a decorator pattern would be better than simple inheritance: with inheritance, for every feature like "processParent", we would have to create an own base class, which can cause problems with multiple features like that.
