### ISSUE TITLE
Introduce processDependencyManagementTransitive to display-dependency-updates

### ISSUE THREAD

**Issue by rweisleder** [mojohaus/versions-maven-plugin#291]
#129 introduced the property `processDependencyManagementTransitive` to dependency-update-report. This property should also be available for display-dependency-updates.

**Comment by sebastianhaberey** [comment]
Yes please :+1:  I just waited 15 minutes for _display-dependency-updates_ to go through all transitive Spring Boot dependencies. Sure, I'll use _dependency-update-report_ for now but it would be nice to have it for _display-dependency-updates_ as well.

**Comment by foal** [comment]
Please!

**Comment by obfischer** [comment]
Especially for Spring Boot projects, this option would be very helpful.

**Comment by daniel-shuy** [comment]
Bump

**Comment by creckord** [comment]
This needs to be reopened. 

I'd also like to extend the request to include the various `use-xxx` commands, which suffer from the same issue and which I find lot handier than display/report. I can just let the plugin update my versions and use git to roll back any undesired updates.

**Comment by stefanseifert** [comment]
i've created a PR (still a draft) as proposal: https://github.com/mojohaus/versions-maven-plugin/pull/588

give it a try, in my tests it works very well with "import" dependencies in the current project. it does not handle them fully as expected in the parent project, still it's a big improvement for projects with lots of transitive dependencies via "import" dependencies.
