### ISSUE TITLE
M2Eclipse complains with "Plugin execution not covered by lifecycle configuration"

### ISSUE THREAD

**Issue by jamietownsend** [mojohaus/versions-maven-plugin#3]
As a developer using M2Eclipse, I see Problems with the text "Plugin execution not covered by lifecycle configuration". These Problems can be avoided by defining an appropriate lifecycle-mapping-metadata.xml file.

**Comment by jamietownsend** [comment]
See https://github.com/mojohaus/versions-maven-plugin/pull/4

**Comment by khmarbaise** [comment]
Has been integrated. Thanks.
