### ISSUE TITLE
Does not check release-only repos when trying to advance from snapshot to newer release

### ISSUE THREAD

**Issue by lcorneliussen** [mojohaus/versions-maven-plugin#30]
When i try to update snapshot versions to the newest release version using `use-latest-versions`, the Maven Versions Plugin doesn't check release repositories for dependencies that currently are using snapshot.

When I set the dependency-repo to snapshots-enabled, it checks the repo and pulls the correct release version.

**Comment by khmarbaise** [comment]
I'm not but it sounds like a misconfiguration not as a bug in versions-maven-plugin? I will close this issue. If you have further detailed information don't hesitate to reopen the issue.
