### ISSUE TITLE
Fix schemaLocation in rules.xml example

### ISSUE THREAD

**Issue by reitzmichnicht** [mojohaus/versions-maven-plugin#306]
Hi

In the documentation of the rules.xml
http://www.mojohaus.org/versions-maven-plugin/version-rules.html

there is still xsi:schemaLocation="http://mojo.codehaus.org/versions-maven-plugin/rule/2.0.0 http://mojo.codehaus.org/versions-maven-plugin/xsd/rule-2.0.0.xsd" which is not valid anymore

Please change to
xsi:schemaLocation="http://mojo.codehaus.org/versions-maven-plugin/rule/2.0.0 http://www.mojohaus.org/versions-maven-plugin/xsd/rule-2.0.0.xsd"

Kind regards,
Michael

**Comment by Stephan202** [comment]
Even better, use the HTTPS variant: `https://www.mojohaus.org/versions-maven-plugin/xsd/rule-2.0.0.xsd` :)

**Comment by famod** [comment]
I just stumbled across the same problem. I created PR #330 to fix it.
