### ISSUE TITLE
update-properties not forcing release versions (allowSnapshots not entirely respected?)

### ISSUE THREAD

**Issue by glianeric** [mojohaus/versions-maven-plugin#33]
Hi,

  I am looking for a switch that allows me to force update-properties to force the property versions to the latest released versions, even if there are newer SNAPSHOTs available.

Currently, if I have a property that says '2.2.1-SNAPSHOT', the update-versions will NOT force 2.2.0, it will leave things as '2.2.1-SNAPSHOT' instead.

allowSnapshots is set to false,

**Comment by glianeric** [comment]
Perhaps better yet, would it be possible to simply add a 'processProperties' switch to the existing goals?

**Comment by henrikno** [comment]
I want this too.
Apparently there was a patch to allow this, which was lost in the codehaus shutdown (MVERSIONS-85).
http://markmail.org/message/7n6ket4zk2svubqx#query:+page:1+mid:7n6ket4zk2svubqx+state:results

There's also a goal called "force-releases" in 2.2, but even that does not downgrade in my case, which seems like a bug.
http://www.mojohaus.org/versions-maven-plugin/force-releases-mojo.html

**Comment by danielmagnussons** [comment]
+1 for the option  "-DallowDowngrade=true"

**Comment by glianeric** [comment]
We did an in-house hack that causes the plugin to downgrade by default when asking for releases (if I ask for the newest releases, why is it giving me SNAPSHOTs anyway?)

If you want the latest snapshot, you simple -DallowSnapshots=true.

**Comment by danielmagnussons** [comment]
What was the in-house hack?  =)

**Comment by glianeric** [comment]
I created this pull request to show the change:

https://github.com/mojohaus/versions-maven-plugin/pull/71

**Comment by danielmagnussons** [comment]
Nice patch, this is how I expected things to work

**Comment by khmarbaise** [comment]
Fixed by https://github.com/mojohaus/versions-maven-plugin/pull/71. If you create a PR you can write something in your log message:
```
Fixed #33
...
````
This will automatically close this issue if the PR is merged..Make my life easier ;-)
