### ISSUE TITLE
Profile based multimodule project fails to update correctly

### ISSUE THREAD

**Issue by KKrzysieq** [mojohaus/versions-maven-plugin#344]
Given this project structure:
-> parent-project
   | --> a-sub-project
   | --> b-sub-project

each sub-project has the below pom:
```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.demo</groupId>
        <artifactId>parent-project</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>sub-project</artifactId>
</project>
```

On the other hand the parent project has this pom:

```<groupId>com.demo</groupId>
    <artifactId>parent-project</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <profiles>
        <profile>
            <id>a-sub-project</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>subproject</name>
                    <value>a</value>
                </property>
            </activation>
            <modules>
                <module>a-sub-project</module>
            </modules>
        </profile>
        <profile>
            <id>b-sub-project</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>subproject</name>
                    <value>b</value>
                </property>
            </activation>
            <modules>
                <module>b-sub-project</module>
            </modules>
        </profile>
    </profiles>
```

When I specify on command line that I want to update the version for the parent and b-sub-project, I would call this:

`mvn -Dsubproject=b versions:set -DnewVersion=1.1-SNAPSHOT`

The result is that I get two poms' versions updated, but not the correct ones - it updates the parent, as expected, but also a-sub-project instead of b-sub-project. Interestingly, running this:

`mvn -Dsubproject=b versions:revert` 

assuming I would've manually or otherwise made the b-sub-project also change version to 1.1-SNAPSHOT and have a pom.xml.versionsBackup file to revert to, the revert operation impacts the correct files - b-sub-project and parent. It looks like versions:set goal will go through subdirectories alphabetically without regard to what's actually supposed to happen.

**Comment by ajarmoniuk** [comment]
> The result is that I get two poms' versions updated, but not the correct ones - it updates the parent, as expected, but also a-sub-project instead of b-sub-project. Interestingly, running this:

The report is invalid. Both submodules are affected by the `set` target. The reason is that the target isn't using Maven to process dependencies and is thus ignoring active profile information. Revert is now actually reverting this behaviour instead of relying on Maven to process submodules, resulting in all affected files being reverted.

@slachiewicz please close.
