### ISSUE TITLE
XML format for property updates report

### ISSUE THREAD

**Issue by KTannenberg** [mojohaus/versions-maven-plugin#359]
XML format was introduced for plugin and dependency update reports in #112/#93. 

However it is rather common and convenient to specify version as a property especially when you a working several dependencies of same version (e.g. in pretty much any Spring application).

Goal `versions:property-updates-report` should allow to specify report format(s) similar to `versions:dependency-updates-report` and `versions:plugin-updates-report`.

**Comment by maxime-michel** [comment]
This is just great, any reason you didn't create a PR with your changes?

**Comment by KTannenberg** [comment]
@maxime-michel, I simply forgot about it :)

Here's PR: #554
