### ISSUE TITLE
Typo in generated XML report for dependency updates

### ISSUE THREAD

**Issue by reallyinsane** [mojohaus/versions-maven-plugin#361]
The XML report for dependency updates contains typos. It would be nice to fix:

- nextVersionAlailable to nextVersionAvailable (fixed with #341 )
- nextIncremetalAvailable to nextIncrementalAvailable (still open)

Best regards

Matthias

**Comment by ajarmoniuk** [comment]
I guess the OP forgot to make a PR out of their commit.
