### ISSUE TITLE
Setting new version is not updating maven session

### ISSUE THREAD

**Issue by YunaBraska** [mojohaus/versions-maven-plugin#368]
I am using a custom maven plugin which helps me to preset the other plugins.
When I change my pom version now and than execute the maven-deploy-plugin, than the plugin is getting my old version from somewhere in the session. I couldn't find the where as I am unable to debug through but would be great if you could update the session. The properties with the old versions are like "artifact", "projectArtifact", "finalName" "project.build.finalName", "attachedArtifacts"

**Comment by khmarbaise** [comment]
If you call lets say `mvn versions:set -DnewVersion=...` and afterwards `mvn deploy` there shouldn't be an issue. But if you try to combine that like this: `mvn versions:set -DnewVersion=... deploy` that will not work. Cause the `pom.xml` will be written to the file system and not reread during that.  One solution might be  https://maven.apache.org/maven-ci-friendly.html
