### ISSUE TITLE
 versions:set is not propagated to submodules if they don't inherit aggregator pom 

### ISSUE THREAD

**Issue by jakub-bochenski** [mojohaus/versions-maven-plugin#37]
If we have a project A with modules B & C where :
- B inherit from A
- C DOESN'T inherit from A

When we execute the following command line :
mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -DnewVersion=0.1

Only A & B are updated.
The fact that C doesn't inherit from A (whereas  C is a module of A) doesn't make it updated. 

Previously known as MVERSIONS-131

**Comment by jakub-bochenski** [comment]
I see this can be achieved by using `-DartifactId='*' ` but this option is not documented anywhere

**Comment by dantran** [comment]
this is not working for me  with -DartifactId='*'.  Basically nothing change to all my poms
i have a module in my module list which does not inherit from main tree. Something like this
    main
      module-1
        pom.xml
      module-2
        pom.xml
      folder-x/module-3
                         pom.xml

module 3 does not inherit from the top parent

**Comment by dantran** [comment]
this is platform specific, on windows,   -DartifactId=*  -DgroupId=*  no single quotes

**Comment by dantran** [comment]
i think this plugin should remove the single quote to deal with windows

**Comment by khmarbaise** [comment]
Hi Dan, have you set `-DoldVersion='*'` ? Furthermore does the module which does not inherit form the main tree has the same group ? If not you have to give `-DgroupId='*'` ..?

**Comment by dantran** [comment]
yes for my case, i need to use

    -DgroupId='*' -DartifactId='*'   on unix/cygwin

    -DgroupId=* -DartifactId=*  on windows

there is no need to use -DoldVersion since i have same version for entire reactor

**Comment by khmarbaise** [comment]
Ok. That means it works for you now correctly. But I think there should be note for using the quotes on Windows vs. Linux/Unix...( added to the docs for groupId, artifactId and oldVersion for the set goal).

**Comment by dantran** [comment]
may be better to trim the surround quotes inside the MOJO?

**Comment by khmarbaise** [comment]
Ok I will open another issue for that purpose.
