### ISSUE TITLE
Children modules get ignored if they're defined as property placeholders

### ISSUE THREAD

**Issue by Knuf** [mojohaus/versions-maven-plugin#379]
Consider a multi-module POM defined like this:
```
<properties>
   <moduleA.name>moduleA</moduleA.name>
   <moduleB.name>moduleB</moduleB.name>
   ...
</properties>
...
<profiles>
   <profile>
      <id>profileA</id>
      <modules>
         <module>../${moduleA.name}</module>
         <module>../${moduleB.name}</module>
         ...
      </modules>
   </profile>
...
</profiles>
```

When running versions-maven-plugin with a command similar to this:
`mvn initialize versions:set -DnewVersion=x.y.z -DprocessAllModules -PprofileA`
both moduleA and moduleB fail to get picked up in the versioning because getReactorModels() method calls getRawModel(), which in turn gets the raw model before any interpolation, so placeholders are not replaced with proper actual values.
Please consider adding a commandline option to properly handle this case.

EDIT: Here's the relevant Maven debug output with [...] indicating redacted absolute paths:

> [INFO] Searching for local aggregator root...
> [DEBUG] Checking to see if [...] is an aggregator parent
> [DEBUG] Local aggregation root is [...]/build
> [INFO] Local aggregation root: [...]/build
> [DEBUG] Finding child modules...
> [DEBUG] Child modules:
> [DEBUG]   ../${moduleA.name}
> [DEBUG]   ../${moduleB.name}
> [DEBUG] Removing child modules which are missing...
> [DEBUG] Removing missing child module ../${moduleA.name}
> [DEBUG] Removing missing child module ../${moduleB.name}
> [DEBUG] After removing missing

**Comment by khmarbaise** [comment]
Do you have an example project ?
