### ISSUE TITLE
Is versions-maven-plugin Maven 3.x compatible?

### ISSUE THREAD

**Issue by nicklasb** [mojohaus/versions-maven-plugin#386]
Hi, 
Can't really find that anywhere, some issues here suggests it, however I am not sure.
Anybody knows?

Kind regards, Nicklas

**Comment by brantgurga** [comment]
Yes, it works. In fact, the current version indicates Maven 3.0 is a required minimum.

**Comment by nicklasb** [comment]
Thanks for your response!
