### ISSUE TITLE
New goals: "versions:update-dependency" and "versions:set-property"

### ISSUE THREAD

**Issue by romani** [mojohaus/versions-maven-plugin#39]
It would be so useful to have a ready to use command line way to update some dependency artifact version in pom.xml to version specified in argument.

Example of command:
```mvn versions:update-dependency -Dartifact="com.puppycrawl.tools.checkstyle" -DnewVersion="6.12.1"```
and it will update version in target pom.xml from any current to "6.12.1"

```mvn versions:set-property -Dproperty="orekit.checkstyle.version" -DnewValue="6.12.1"```
and it will update value of property in target pom.xml from any current to "6.12.1"

Use case: https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L72 we need to update version of certain dependency from old to current SNAPSHOT to make a integration testing.

Right now we use magic of "sed" and other utils.

**Comment by mgreau** [comment]
+1

**Comment by kkyriakidis** [comment]
Same problem here.
I need to change the versions of the project dependencies back to SNAPSHOT

**Comment by pbromley** [comment]
+1
Looks like this pull request does what we want - https://github.com/mojohaus/versions-maven-plugin/pull/18

**Comment by khmarbaise** [comment]
Done with #18

**Comment by oreporan** [comment]
Made a pull request to solve the versions:set-property issue
https://github.com/mojohaus/versions-maven-plugin/pull/124
