### ISSUE TITLE
use-dep-version (and other goals) does not handle the import-scoped dependency

### ISSUE THREAD

**Issue by JohnWu-Pro** [mojohaus/versions-maven-plugin#395]
* `versions:use-dep-version` does not update the version of the import-scoped dependency, in the `<dependencyManagement>` section. Other goals may also not handle import-scoped dependency correctly.
* This issue might be related to [Include import-scoped dependency in dependency plugin goals](https://issues.apache.org/jira/browse/MDEP-694)

**Comment by janhicken** [comment]
This seems to be a duplicate of #346. 
The `PomHelper` already features a method to find the imported POMs inside the dependency management section. This is just not used in many of this plugin's goals. The commit referenced in #346 shows a possible fix for the goal `use-latest-releases`.

**Comment by cemo** [comment]
Same for `versions:compare-dependencies. I would like to compare my dependencies which is imported into the project with the remote pom.

**Comment by frode-carlsen** [comment]
I've createad a PR that also will update the import scoped dependencies for the following goals:
* use-dep-version
* use-latest-versions
* use-latest-snapshots
* use-latest-release
* use-next-releases
* use-next-versions
* use-next-snapshots
