### ISSUE TITLE
Upgrade mojo-parent version 60

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/versions-maven-plugin#419]

**Comment by mfriedenhagen** [comment]
Hello @khmarbaise, I just release 2.8.2 with the old mojo-parent, mojo-parent 60 has problems with cobertura, so better stay with this one. As we only do lazy consensus here anyways, releasing is not that much of a burden here.

**Comment by khmarbaise** [comment]
@mfriedenhagen Yes of course. go for it.
