### ISSUE TITLE
how to update dependency version by property in pom.xml? It seems not work

### ISSUE THREAD

**Issue by cnscud** [mojohaus/versions-maven-plugin#425]
my current pom.xml 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <parent>
        <groupId>com.***.example</groupId>
        <artifactId>example-root-pom</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>com.***.example</groupId>

    <artifactId>test-mymvnversion</artifactId>
    <version>1.1.1-SNAPSHOT</version>
    <name>test-mymvnversion</name>

    <modules>
        <module>submodtest</module>
    </modules>

    <properties>
        <afeaturemod.version>1.3.0</afeaturemod.version>
    </properties>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>com.***.example</groupId>
                <artifactId>submodtest</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.***.example</groupId>
                <artifactId>afeaturemod</artifactId>
                <version>[${afeaturemod.version}]</version>
            </dependency>

     
        </dependencies>
    </dependencyManagement>

</project>

----------------
1.  mvn versions:use-next-snapshots  not work, the version of "afeaturemod" was not updated.

[INFO] --- versions-maven-plugin:2.8.1:use-next-snapshots (default-cli) @ test-mymvnversion ---
[INFO] Incremental version changes allowed
[INFO] Ignoring reactor dependency: com.***.example:submodtest:jar:1.1.1-SNAPSHOT
[INFO] Ignoring com.***.example:afeaturemod:jar:[1.3.0] as the version number is too short
[INFO] Incremental version changes allowed

2. if I use normal version define , it works.

if I use: 

 <dependency>
    <groupId>com.***.example</groupId>
    <artifactId>afeaturemod</artifactId>
    <version>1.3.0</version>
</dependency>

3.  works fine  :  
    mvn versions:update-properties  

thanks.

**Comment by cnscud** [comment]
with the 2.8.1 plugin.

                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.8.1</version>

**Comment by AYWWWWW** [comment]
> with the 2.8.1 plugin.
> 
> ```
>             <groupId>org.codehaus.mojo</groupId>
>             <artifactId>versions-maven-plugin</artifactId>
>             <version>2.8.1</version>
> ```

it happened to me too.
