### ISSUE TITLE
error parsing <Xlint:unchecked/>

### ISSUE THREAD

**Issue by THausherr** [mojohaus/versions-maven-plugin#429]
I updated to 2.8.1 from 2.7 and have trouble with this in my pom.xml
```
                    <compilerArguments>
                        <Xlint:unchecked/>
                        <verbose/>
                    </compilerArguments>
```
Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.8.1:display-plugin-updates (default-cli) on project XXXX: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.8.1:display-plugin-updates failed: Error parsing XXXXX\pom.xml: Undeclared namespace prefix "Xlint"

**Comment by jojochuang** [comment]
Reproducible when building Hadoop trunk
https://github.com/apache/hadoop/blob/6857a05d6ac566a60336c0a28951f09ecda39f24/hadoop-project/pom.xml#L2288
