### ISSUE TITLE
update-parent goal ignores version range when allowing snapshots

### ISSUE THREAD

**Issue by JasonWThompson** [mojohaus/versions-maven-plugin#438]
Consider the following command:

```
 mvn org.codehaus.mojo:versions-maven-plugin:2.8.1:update-parent "-DparentVersion=(,5)" "-DallowSnapshots=true"
```

The anticipated behavior is that the parent pom version should be updated to the latest version that is less than version 5. Instead the following happens.

```
❯ mvn org.codehaus.mojo:versions-maven-plugin:2.8.1:update-parent "-DparentVersion=(,5)" "-DallowSnapshots=true"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.XXXXX:XXX-XXX-XXXX >-------------------
[INFO] Building XXX-XXX-XXXX 2.2-SNAPSHOT
[INFO] --------------------------------[ rpm ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.8.1:update-parent (default-cli) @ XXX-XXX-XXXX ---
[INFO] Updating parent from 4.1 to 5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.366 s
[INFO] Finished at: 2020-10-28T08:32:46-05:00
[INFO] ------------------------------------------------------------------------
```

I expected it to update to 4.4-SNAPSHOT (the latest 4.x version deployed).

**Comment by pzygielo** [comment]
> I expected it to update to 4.4-SNAPSHOT (the latest 4.x version deployed).

I think - your expectation - or `parentVersion` - need to be adjusted:
```
$ java -jar maven-artifact-3.6.3.jar 5.0-SNAPSHOT 5.0
Display parameters as parsed by Maven (in canonical form) and comparison result:
1. 5.0-SNAPSHOT == 5-snapshot
   5.0-SNAPSHOT < 5.0
2. 5.0 == 5
```
Currently you allow SNAPSHOTs and all versions < 5.0, which 5.0-SNAPSHOT satisfies.

**Comment by JasonWThompson** [comment]
Hi @pzygielo,

In hindsight that makes sense. Snapshots always comes before releases and therefore even though I'm specifying that I want everything before 5.0, 5.0-SNAPSHOT would qualify. Thank you for clarifying. I was able to make an adjustment and it works as expected. I appreciate the clarification.
