### ISSUE TITLE
 String index out of range: 9 for mvn versions:display-dependency-updates -Dmaven.version.rules=rules.xml 

### ISSUE THREAD

**Issue by ghost** [mojohaus/versions-maven-plugin#439]
This goes wrong in:
https://github.com/mojohaus/versions-maven-plugin/blob/efee2d1295b66210cbd901b15067688adc142c81/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java#L404

If the given argument is shorter then "classpath", it tries to get a character at an index which is outside the String.

**Comment by ghusta** [comment]
A workaround would be to have a input string longer than 9 characters.

For example instead of "rules.xml" you can try "file:./rules.xml"
