### ISSUE TITLE
[feature] add an option to update Reproducible Build project.build.outputTimestamp while updating version

### ISSUE THREAD

**Issue by hboutemy** [mojohaus/versions-maven-plugin#453]
Reproducible Builds require to define a timestamp for jars zip entries. https://maven.apache.org/guides/mini/guide-reproducible-builds.html
Having a fixed value is not nice: Maven Release Plugin helps updating the value at release time.

Instead of using Maven Release Plugin, some users prefer custom scripts and use versions:set to easily update versions in pom.xml: adding an option to update the timestamp at the same time would give them a nice help for Reproducible Builds

**Comment by garydgregory** [comment]
Yes, please. I use custom scripts to manage releases over at Apache Commons.
