### ISSUE TITLE
version properties are not resolved for dependency-updates-report when processDependencyManagementTransitive disabled

### ISSUE THREAD

**Issue by jellisgwn** [mojohaus/versions-maven-plugin#459]
Preconditions:
- multi-module project
- processDependencyManagementTransitive = false
- versions defined in properties

If a multi-module project defines properties for versions they are not resolved in the report output. Meaning that report shows the property name not the property value (the version), but only when the processDependencyManagementTransitive flag is false.

**Comment by jellisgwn** [comment]
https://github.com/mojohaus/versions-maven-plugin/pull/460

**Comment by jellisgwn** [comment]
Is anything more needed to get the associated PR merged?

**Comment by bmarwell** [comment]
will look at it. Appreciated if you could squash it and add `[#459] ` in front of the commit message.
