### ISSUE TITLE
Allow dependency-updates-report to configure processDependencies and processDependencyManagement like display-dependency-updates can

### ISSUE THREAD

**Issue by bbrouwer** [mojohaus/versions-maven-plugin#46]
When using Spring Boot, the dependency management section of my project gets to be enormous. It can take a medium sized project an extra 30 minutes to generate the site because of this. I want to be able to set `processDependencyManagement` to `false` to speed up site generation. 

When I run display-dependency-updates on my project, it only adds about 2 minutes to the total build time when I set `processDependencyManagement` to `false`.

**Comment by PeterWippermann** [comment]
In #129 I have a similar request. Wouldn't it be nice to have a ternary switch?

"Process dependency management section?"
1. All
2. Only top level, no transitive or imports
3. No

**Comment by khmarbaise** [comment]
Hm.After taking a deeper look into the pull request I see at a larger number of  different things which are solved in this PR. It looks as if you have not correctly rebased your branch and made a new pull request so to see only the changes you have made...I'm not sure here cause I see changes which are made on an branch for maven 3 migration which should never be part of the current mast at the moment....

**Comment by khmarbaise** [comment]
I have taken the liberty to use your code suggestions and added them. Based on your pull request which looks wrong I couldn't integrate it directly. None the less thanks for your contribution.

**Comment by PeterWippermann** [comment]
Too bad that you didn't incorporate may feedback from above, @khmarbaise.
And regarding your code attribution, I'm also not sure whether @cs01lg and @bbrouwer are the same person?!

**Comment by khmarbaise** [comment]
Hi @PeterWippermann you are talking about the hint for import scope ?

**Comment by PeterWippermann** [comment]
yes, why not add an option to process only the top-level dependencies in the POM and exclude their transitive dependencies?

**Comment by khmarbaise** [comment]
Ah..If I correctly see this is #129 ?

**Comment by bbrouwer** [comment]
Nope. I'm not the same person as @cs01lg 

I like the request of #129 as it sounds like a better request than mine here. My situation is the same: Spring Boot with importing a pom's dependencies.

**Comment by khmarbaise** [comment]
@bbrouwer Please take a look at #129 and the output of an example run...
