### ISSUE TITLE
Is it possible to check for new versions (sshot, prod, whatever) in parallel

### ISSUE THREAD

**Issue by ineffective** [mojohaus/versions-maven-plugin#464]
It seems that by default plugin is single threaded when it comes to checking for updates in main repository. We have Artifactory server that serves as an internal package repository and which also mirrors (obviously?) few external packages. Each run of versions plugin is very slow - judging from maven output check for new versions are done one by one - is it possible to somehow force plugin to check N (preferably configurable) packages in parallel? Something along the lines `-DrepoQueryWorkerThreads=10` or similar. There are days that we have to run such update few times a day and each check takes anywhere from 5 to 15 minutes, which is prohibitively long.

**Comment by istvan-derda** [comment]
This would be a great improvement!

**Comment by slawekjaranowski** [comment]
@istvan-derda please retest with the latest version of plugin - we have done many improvements
