### ISSUE TITLE
Remove not needed calls to toString()

### ISSUE THREAD

**Issue by obfischer** [mojohaus/versions-maven-plugin#466]
I would like to help to improve the code base of the Versions plugin and therefore I would like to suggest to remove all not needed calls to toString() in the code base. 

Even if this is a small change and it might not be an issue, I think it will help to improve the readability and the quality of the code.

**Comment by bmarwell** [comment]
Hi @obfischer,,
sure!

Please make sure you use a branch which is branched of master, and the new branch having no other commits than those concerning this issue.
The commit messages should include the issue number and a short description, e.g.

* `[#466] remove unneeded calls to \`toString()\`` or
* `Fixes #466: remove unneeded calls to \`toString()\``

From what I see in your branch, you were committing to master and have other commits mixed in, e.g. merged some dependabot updates.

**Comment by obfischer** [comment]
Hi @bmarwell, 
I fixed the branch history and my pull requests contains now only one commit.

But somehow I am unable to link my pull request to this issue. The commit message in the commit in the branch is

````
Fixes #466
o Removed not needed calls to toString() to improve the code base
````

Any idea why pull request and issue are not linked automatically by Github?

**Comment by pzygielo** [comment]
> Any idea why pull request and issue are not linked automatically by Github?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue:

> You can link an issue to a pull request manually or using a supported keyword __in the pull request description__.

**Comment by obfischer** [comment]
Thank you @pzygielo, I recreated the pull request as it seems not possible to add the issue afterwards to the description.

**Comment by pzygielo** [comment]
>  as it seems not possible to add the issue afterwards to the description.

Not saying it's the reason, but perhaps due to [typo](https://github.com/mojohaus/versions-maven-plugin/pull/467#issuecomment-869151332).

**Comment by obfischer** [comment]
🙇🏻‍♂️
