### ISSUE TITLE
Migrate from JUnit 4 to JUnit 5

### ISSUE THREAD

**Issue by obfischer** [mojohaus/versions-maven-plugin#472]
Writing tests is the hardest part in maintaining long-living software projects. Therefore, we should have the best tools available. So, the versions plugin should use JUnit 5 instead of JUnit 4.

**Comment by obfischer** [comment]
Please don't close this issue after merging pull request #473. I would like to re-use this issue for some more pull requests.

**Comment by bmarwell** [comment]
> Please don't close this issue after merging pull request #473. I would like to re-use this issue for some more pull requests.

-1 – You can create an issue for migrating specific unit tests, where this issue only migrates the testing engine. The benefits would be more in-detail documentation why a particular test was migrated. 
Over at apache ppl say "don't change stuff if it is not broken". I can see good reasons for migrating unit tests, though. Just document a group of tests in their own issue (my opinion).

**Comment by obfischer** [comment]
I see the point, but IMHO code must be touched and always improved, as if you don't do it, you will reach the point, there you simply think: I don't want to touch this old crap, let us kick it. I know there is something in the middle, but I would prefer to improve things is it adds value.

**Comment by bmarwell** [comment]
If you see "old crap" it got past a code review when it shouldn't have.
You're welcome to refactor such code. But I don't think *every* junit4 test needs to be converted just now. The syntax is very similar.

**Comment by olamy** [comment]
It’s not closed because code is still using old junit api 😜

**Comment by bmarwell** [comment]
https://github.com/mojohaus/versions-maven-plugin/issues/472#issuecomment-882784900

But if you insist, we can use this one for also tracking unit test conversions...
