### ISSUE TITLE
Update the <connection>, <developerConnection> and <url> sections inside <scm>

### ISSUE THREAD

**Issue by setedivento** [mojohaus/versions-maven-plugin#477]
**[This is a feature request.]**

As per Title, I would like to be able to update the `<connection>`,`<developerConnection>` and `<url>` sections inside the `<scm>` tag in the pom.

It seems you already did something in this direction; in particular, I am referring to this issue: https://github.com/mojohaus/versions-maven-plugin/issues/182,
which corresponding goal is documented here:
https://www.mojohaus.org/versions-maven-plugin/set-scm-tag-mojo.html

What I am asking for is to fill the remaining gap, as indeed pointed out in this comment:
https://github.com/mojohaus/versions-maven-plugin/issues/182#issuecomment-315526534

Maybe a more generic `update-scm` goal could be added?
Or even a series of `set-scm-url`, `set-scm-connection`, `set-scm-developer-connection` goals would be fine.

Thank you very much!

**Comment by setedivento** [comment]
I know SVN is a little bit outdated nowadays, but can someone please have a look at this?
Thank you.

**Comment by ajarmoniuk** [comment]
Sure.

**Comment by setedivento** [comment]
> Sure.

Thanks so much!
