### ISSUE TITLE
[Bug] The command line 'mvn versions:set' returns exit code 1 with the last maven version 3.8.2

### ISSUE THREAD

**Issue by RomainPruvostMHH** [mojohaus/versions-maven-plugin#483]
Hi,

I have a shell script who runs the command line 'mvn versions:set' and verify the exit code. With my previous Maven 3.6.3, everything works fine.
But I recently upgraded maven to 3.8.2, and now the command line 'mvn versions:set' returns exit code 1 systematically. I precise that the result of the mvn command is BUILD SUCCESS of course.

```
  mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$mvn_new_version
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
    echo "ERROR : cmd mvn versions:set -DnewVersion=$mvn_new_version failed"
    exit 10
  fi
```

Any idea ?

Kind regards,
Romain

**Comment by slawekjaranowski** [comment]
Can you show output of:

    mvn -V versions:set -DnewVersion=1.2.3; echo "result=$?"

I can't see a problem - works for me 😄

**Comment by RomainPruvostMHH** [comment]
Hi @slawekjaranowski,

I reproduce the problem with the minimum of files. 

With maven 3.6.3, it's ok :
![maven-3 6 3-result-ok](https://user-images.githubusercontent.com/76999857/130659400-85c2addf-3c1f-434a-bf32-883b3c1bb3ab.PNG)


With maven 3.8.2, it's KO :
![maven-3 8 2-result-ko](https://user-images.githubusercontent.com/76999857/130659452-c232add5-e020-463b-9c7c-f113de4ec49c.PNG)

**Comment by slawekjaranowski** [comment]
ok, last simply test:

     mvn -v; echo "result=$?"

**Comment by RomainPruvostMHH** [comment]
![maven-commands-results](https://user-images.githubusercontent.com/76999857/130807103-286037e5-6806-42cd-87dd-3092dec6e320.PNG)

**Comment by slawekjaranowski** [comment]
I don't have any more quick idea ... can you share your test project

**Comment by raphaelNguyen** [comment]
I also have had this problem. I was on Maven 3.8.1 which was fine. After upgrading to 3.8.2, I started having my scripts failing and noticed the problem. Was able to reproduce it with a very minimalist project with no code and just a pom as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.test</groupId>
  <artifactId>test</artifactId>
  <version>1.0</version>
</project>
```

All these are done on the same version of `versions-maven-plugin` so maybe this is some weird interaction with the new version of maven? Please tell me if I can provide any more information.

**Comment by slawekjaranowski** [comment]
Only out of my curiosity - can anyone trigger build on master branch - now GitHub runners should have Maven 3.8.2

**Comment by slawekjaranowski** [comment]
You can also create issue at Apache Jira for Maven project:
https://issues.apache.org/jira/projects/MNG

**Comment by RomainPruvostMHH** [comment]
@slawekjaranowski So, you are sure the problem is at Maven and is not at versions plugin ?

**Comment by slawekjaranowski** [comment]
I'm not sure - where is the problem but Maven 3.8.2 exposes it ... 
I don't have access to host with windows os so I can't reproduce it

Maybe someone else can help with it, I think it is good idea to post on Maven Developers list or create issue at Maven jira.

I heard that new Maven version 3.8.x will be prepared to the end of month - so maybe fix (if needed) will be catched

**Comment by RomainPruvostMHH** [comment]
Issue at Apache Maven :

https://issues.apache.org/jira/browse/MNG-7234

**Comment by michael-o** [comment]
Need to take a look at it. This is weird. There have been virtually no changes to the startup scripts of Maven in 3.8.2.

**Comment by michael-o** [comment]
Hmmm:
```
$ ~/apache-maven-3.8.2/bin/mvn -V versions:set -DnewVersion=3 ; echo $?
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /net/home/osipovmi/apache-maven-3.8.2
Java version: 1.8.0_302, vendor: OpenJDK BSD Porting Team, runtime: /usr/local/openjdk8/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "freebsd", version: "12.2-stable", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< com.test:test >----------------------------
[INFO] Building test 2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.8.1:set (default-cli) @ test ---
[INFO] Local aggregation root: /net/home/osipovmi
[INFO] Processing change of com.test:test:2 -> 3
[INFO] Processing com.test:test
[INFO]     Updating project com.test:test
[INFO]         from version 2 to 3
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.197 s
[INFO] Finished at: 2021-09-07T12:56:26+02:00
[INFO] ------------------------------------------------------------------------
```

Will try MinGW...

**Comment by michael-o** [comment]
MinGW:
```
$ /c/Entwicklung/Programme/apache-maven-3.8.2/bin/mvn -V versions:set -DnewVersion=4 ; echo $?
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: C:\Entwicklung\Programme\apache-maven-3.8.2
Java version: 1.8.0_275, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-8\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< com.test:test >----------------------------
[INFO] Building test 2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.8.1:set (default-cli) @ test ---
[INFO] Local aggregation root: C:\Users\osipovmi
[INFO] Processing change of com.test:test:2 -> 4
[INFO] Processing com.test:test
[INFO]     Updating project com.test:test
[INFO]         from version 2 to 4
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.563 s
[INFO] Finished at: 2021-09-07T13:03:19+02:00
[INFO] ------------------------------------------------------------------------
1
```

**Comment by michael-o** [comment]
OK, here is the bug (swallowed exceptions) and it in Cygwin only. @gnodet needs to take a look.

<img width="935" alt="Affected object" src="https://user-images.githubusercontent.com/573017/132348565-d41816c3-394c-45cd-b828-e4484abe76cd.png">
<img width="960" alt="Flush buffer" src="https://user-images.githubusercontent.com/573017/132348625-99d147b4-c339-4f36-9051-3b104d62051c.png">
<img width="960" alt="Invalid handle" src="https://user-images.githubusercontent.com/573017/132348767-9dc8ffed-68e5-47b2-97bf-f349df74a2e7.png">

Invalid handle...

**Comment by michael-o** [comment]
Note that happens only in MinGW. It does not fail in PowerShell as well as Windows Command Prompt.

**Comment by michael-o** [comment]
Debugged a bit further, MinGW (MSYS2) assignes handles 1112 to both `stdout` and `stderr` while PowerShell does 84 and 88. Something is either flawed in MSYS2 or in Jansi. So without @gnodet no progress.

**Comment by gnodet** [comment]
@michael-o which call throws the invalid handle exception exactly ?
The `uninstall` should not close the streams, so the handle should not become invalid...
The `1112` is the file descriptor of the underlying `FileOutputStream` ?

**Comment by michael-o** [comment]
When I enter `flushBuffer()` specifically `out.write(buf, 0, count);` fails with the invalid handle.
`1112` is not the FD, but the handle. The fd is `-1` in this case. I guess Windows uses the handle.

**Comment by gnodet** [comment]
I think the problem is located here:
https://github.com/codehaus-plexus/plexus-interactivity/blob/master/plexus-interactivity-api/src/main/java/org/codehaus/plexus/components/interactivity/DefaultOutputHandler.java#L53

The `DefaultOutputHandler` should not close the `consoleWriter` because it will also close the underlying `System.out` print stream.  Those system streams are not supposed to be closed directly.

**Comment by gnodet** [comment]
See https://github.com/codehaus-plexus/plexus-interactivity/pull/3 for a possible fix.

**Comment by michael-o** [comment]
Thank you @gnodet I will check tomorrow.

**Comment by michael-o** [comment]
Checked now. I can confirm @gnodet's analysis and it correct. Thank you for that. So this is not a bug in Maven or Jansi, they just trigger the bug in Plexus Interactivity.

**Comment by michael-o** [comment]
Plexus Interactivity 1.1 has been pushed to Central. Please update at the earliest convenience.

**Comment by gnodet** [comment]
PR for maven https://github.com/apache/maven/pull/536
