### ISSUE TITLE
Versions specified by properties are not replaced (in use-latest-snapshots)

### ISSUE THREAD

**Issue by pkasarski** [mojohaus/versions-maven-plugin#50]
In my POM, most versions are specified as properties, e.g.:

```
<properties>
        <base.version>01.05.12</base.version>
</properties>

<dependencies>
            <dependency>
                <groupId>com.example.base</groupId>
                <artifactId>common</artifactId>
                <version>${base.version}</version>
            </dependency>
</dependencies>
```

For such versions, `versions:use-latest-snapshot` does not make any replacements. In other words, the version in the example dependency is not changed to use the snapshot. Is this the intended behavior? If so, why?

**Comment by foal** [comment]
I have the same issue. Did you found any workaround?

**Comment by stonecauldron** [comment]
I have the same problem and do not understand why this happens.

**Comment by khmarbaise** [comment]
This will happen cause using a property is something different than using a version in dependencies directly..For such kind of upgrade you should use the goal [`update-property`](http://www.mojohaus.org/versions-maven-plugin/update-property-mojo.html) where you need to give `-DallowSnapshots=true` is the newer version you expect to be a SNAPSHOT. So i will close this issue cause it's a problem...
