### ISSUE TITLE
The plugin doesn't build with updated properties  

### ISSUE THREAD

**Issue by QiyuZ** [mojohaus/versions-maven-plugin#504]
I 'm meeting exact the same issue as https://stackoverflow.com/questions/45179530/versions-maven-plugin-doesnt-build-with-updated-properties
I created the execution during the build using update-property and set the phase as validate 
So when I do like ```mvn install``` , I can see in the log,the property has been update and the pom file has been overwritten by expected value.
However, during the real build, it still uses the old property. So I have to separate the mvn command into 2, that update property and then do the build, just like the questions in the stackoverflow
Not sure if it's mvn (I'm using mvn 3.6) or plugin's issue, or it's just designed like that?

**Comment by ajarmoniuk** [comment]
Well, this is how Maven works, it's not a plugin issue. You're executing the plugin which is modifying the POM file, but the remaining targets are still using the already loaded POM. Won't fix IMO. @slachiewicz
