### ISSUE TITLE
NullPointerException on versions:set with inherited groupId

### ISSUE THREAD

**Issue by qualidafial** [mojohaus/versions-maven-plugin#51]
When groupId is omitted (read: inherited from parent pom), `mvn versions:set` fails with an NPE.

Workaround: set the `groupId` explicitly.

http://stackoverflow.com/questions/29995139/maven-versions-maven-plugin-versions-plugin-2-2

**Comment by falbrech-hsdg** [comment]
As far as I can see, this is already fixed in this repository, but there is no release containing this fix yet. 

This is the fixing commit: c47721908a0efc9d3f19113d0a60784a8c5dd175

**Comment by PatrickSauts** [comment]
Voting for that bug fixed to be released, please.

**Comment by mellster2012** [comment]
+1

**Comment by camiloking** [comment]
+1

**Comment by qualidafial** [comment]
Attention GitHubbers: use the reaction emoji thingy at the top right of each comment, rather than spamming issues with "+1" comments
