### ISSUE TITLE
allowMajorUpdates Parameters for update-properties Maven Goal

### ISSUE THREAD

**Issue by emoshaya-cognito** [mojohaus/versions-maven-plugin#53]
I've noticed versions:update-properties goal is missing the following optional parameters that are available to the use-latest-versions goal:

allowIncrementalUpdates: Whether to allow the incremental version number to be changed.
allowMajorUpdates: Whether to allow the major version number to be changed.
allowMinorUpdates: Whether to allow the minor version number to be changed.

Is there any way to use these parameters with the versions:update-properties goal?

**Comment by mjustin** [comment]
I too would like to see this, and it feels like the two goals should be consistent in this manner.

**Comment by derkd** [comment]
+1

**Comment by hillmanytli** [comment]
+1 also
These are very useful parameters. use-latest-versions and its variants cannot update properties and; update-properties can only change version to the latest value. There is a gap here.

**Comment by bcdewit** [comment]
+1

**Comment by pdegeus** [comment]
+1 Not auto-updating to the next major version (which would have breaking API changes) is important..

**Comment by smeierhofer** [comment]
+1

**Comment by markcuk** [comment]
+1

**Comment by darrenyeats** [comment]
+1

**Comment by darrenyeats** [comment]
+1

**Comment by darrenyeats** [comment]
+1.

**Comment by khmarbaise** [comment]
This issue is already fixed.
