### ISSUE TITLE
support to increase x or y in version of x.y.z, not only z

### ISSUE THREAD

**Issue by valuetodays** [mojohaus/versions-maven-plugin#539]
Assume current version is 1.0.0-SNAPSHOT.

I can set version to 1.0.1-SNAPSHOTby `mvn versions:set -DnextSnapshot`.
In math, I can set version to the following:
- 1.0.1-SNAPSHOT (finished yet)
- 1.1.0-SNAPSHOT
- 2.0.0-SNAPSHOT

I think it's useful.

**Comment by ajarmoniuk** [comment]
I'll do it

**Comment by cordahi** [comment]
Would it be possible to change the behaviour of this feature to follow standard semantic versioning?
I recently opened https://github.com/mojohaus/versions/issues/1021

If starting from version `1.2.3-SNAPSHOT`,
- `mvn -DnextSnapshot -DnextSnapshotIndexToIncrement=2 versions:set` should result in version `1.3.0-SNAPSHOT`
- `mvn -DnextSnapshot -DnextSnapshotIndexToIncrement=1 versions:set` should result in version `2.0.0-SNAPSHOT`

What is the use case of the current behaviour that preserves the rightmost digits?
