### ISSUE TITLE
support to get command

### ISSUE THREAD

**Issue by valuetodays** [mojohaus/versions-maven-plugin#540]
Assume a pom.xml snippet:

```xml
    <parent>
        <groupId>foo</groupId>
        <artifactId>bar</artifactId>
        <version>1.0.0</version>
    </parent>
```

I get the version 1.0.1 by `xmllint`(a linux command tool, `sudo yum install -y libxml2`,  `xmllint --xpath "/*[name()='project']/*[name()='version']/text()" pom.xml`).

I think versions-maven-plugin can support the same funtion just like `mvn  versions:get [-DgetParentVersion=true] [-DgetProjectVersion=true] -DgetVersionFromGroupIdAndArtifactId=foo.bar`

**Comment by khmarbaise** [comment]
There is an much easier way to get the version number from a maven build:
```
VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
```
or:
```
VERSION=$(mvn help:evaluate -Dexpression=project.parent.version -q -DforceStdout)
```

**Comment by valuetodays** [comment]
Thanks @khmarbaise
