### ISSUE TITLE
display-dependency-updates should fallback to others scopes if there is no new version

### ISSUE THREAD

**Issue by sfragata** [mojohaus/versions-maven-plugin#553]
The 3 parameters `allowIncrementalUpdates`, `allowMajorUpdates` and `allowMinorUpdates` are mutually exclusive. 
if I enable major updates (`allowMajorUpdates=true`)and there is no one it should show me the minor or the incremental updates, if `allowMinorUpdates=true` and `allowIncrementalUpdates=true`, The same will be if I enable `allowMinorUpdates` and there is no new version for this scope it should propose incremental one if `allowIncrementalUpdates=true`

**Comment by ajarmoniuk** [comment]
Resolved by #283

**Comment by ajarmoniuk** [comment]
@slachiewicz please close

**Comment by ajarmoniuk** [comment]
The goals will not fall back to other scopes if no version is found -- that would be quite unexpected for most users. However, #283 has clarified the semantics of those switches, which, as you noticed, aren't really independent.

**Comment by sfragata** [comment]
After comment of @ajarmoniuk 
`Resolved by [#283](https://github.com/mojohaus/versions-maven-plugin/issues/283)`
and
`The goals will not fall back to other scopes if no version is found -- that would be quite unexpected for most users. However, [#283](https://github.com/mojohaus/versions-maven-plugin/issues/283) has clarified the semantics of those switches, which, as you noticed, aren't really independent.`

I'm gonna close it
