### ISSUE TITLE
Goal displayPluginUpdates generates incorrect warnings on the <prerequisites> section for non-plugin projects

### ISSUE THREAD

**Issue by kwin** [mojohaus/versions-maven-plugin#56]
If I check a project for plugin updates which is of type "pom" (i.e. it only acts as a parent pom), the versions-maven-plugin generates incorrect warnings like

```
[ERROR] Project requires an incorrect minimum version of Maven.
[ERROR] Either change plugin versions to those compatible with 2.2.1
[ERROR] or update the pom.xml to contain
[ERROR]     <prerequisites>
[ERROR]       <maven>3.1.0</maven>
[ERROR]     </prerequisites>
```

followed by INFO messages like 

   [INFO] Require Maven 3.0 to use the following plugin updates:
   [INFO]   maven-source-plugin ........................................... 3.0.0

Both messages are wrong for all projects which are not of type "maven-plugin", because the `<prerequisites>` section is only meant for plugins (see [MNG-5501](https://issues.apache.org/jira/browse/MNG-5501) and [MNG-5297](https://issues.apache.org/jira/browse/MNG-5297)). Since Maven 3 this is no longer enforced in any way for non-plugin packagings and has recently been clarified in the docs as well (http://maven.apache.org/ref/3.3.9/maven-model/maven.html#class_prerequisites)
Either remove those warnings or instead emit a warning that `maven-enforcer-plugin` should be used to enforce a specific Maven version.

**Comment by garretwilson** [comment]
This just got even worse: now that Maven 3.5.0 is out, it will complain if we use `<prerequisites>` in a non-plugin project.

So we can't win for losing. `versions-maven-plugin` complains that there is no `<prerequisites>` section. If we add it, Maven 3.5.0 complains that there _is_ a `<prerequisites>` section.

**Comment by garretwilson** [comment]
Wait, this is closed? I'm confused. What am I supposed to do with Maven 3.5.0? Do I need `<prerequisites>` or not?

**Comment by michael-o** [comment]
Unless your project is a `maven-plugin`, just leave it out.

**Comment by garretwilson** [comment]
> Unless your project is a maven-plugin, just leave it out.

But if I leave it out, I can no longer check for plugin updates using `mvn versions:display-plugin-updates` because this plugin is so broken that it _requires_ `<prerequisites>` (even though that is wrong in a non-plugin project). See #173. This is really no-win situation.
