### ISSUE TITLE
-Dversions.outputFile argument fails to write file introduced in 2.9.0

### ISSUE THREAD

**Issue by jcamerin** [mojohaus/versions-maven-plugin#567]
This issue seems to be introduced in version 2.9.0 of the versions plugin.  Using version 2.8.1 the output file is generated.

20:01:20  + mvn versions:display-plugin-updates -Dversions.outputFile=pluginReport.txt
20:01:20  ----- withMaven Wrapper script -----
20:01:20  Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/fs/workspace/Application Reports/Accelerator Dependency Report@tmp/withMavenaac03040/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/fs/workspace/Application Reports/Accelerator Dependency Report@tmp/withMavenaac03040" 
20:01:20  Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
20:01:20  Maven home: /home/jenkins/fs/tools/hudson.tasks.Maven_MavenInstallation/M3.5
20:01:20  Java version: 1.8.0_312, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-1.amzn2.0.2.x86_64/jre
20:01:20  Default locale: en_US, platform encoding: UTF-8
20:01:20  OS name: "linux", version: "4.14.256-197.484.amzn2.x86_64", arch: "amd64", family: "unix"

Using versions plugin 2.9.0, I get the following error:
20:03:29  [ERROR] Cannot send output to /home/jenkins/fs/workspace/Application Reports/Accelerator Dependency Report/pluginReport.txt
20:03:29  java.nio.file.NoSuchFileException: /home/jenkins/fs/workspace/Application Reports/Accelerator Dependency Report/pluginReport.txt

**Comment by stefanseifert** [comment]
looks like a duplicate of #542, fixed with #547 in next release

**Comment by jcamerin** [comment]
Yup, I agree.  I missed in my search for issues.  Closing this issue
