### ISSUE TITLE
Make update of the outputTimestamp configurable

### ISSUE THREAD

**Issue by aleksandr-m** [mojohaus/versions-maven-plugin#568]
There are cases when `project.build.outputTimestamp` shouldn't be updated - [see this issue](https://github.com/aleksandr-m/gitflow-maven-plugin/pull/310).

Please make it configurable with some property.

**Comment by stefanseifert** [comment]
i propose this PR as fix: https://github.com/mojohaus/versions-maven-plugin/pull/570
