### ISSUE TITLE
'update-property' goal does not recognize a property is used in <dependencyManagement>

### ISSUE THREAD

**Issue by tazle** [mojohaus/versions-maven-plugin#57]
When using update-property goal to update dependency versions specified through properties, it does not recognize that the property is used to specify versions in <dependencyManagement> section of the build. It should.

**Comment by khmarbaise** [comment]
Can you create a full working example and the commands you have used to test? And the results you expect? (Best would be a github project...)..

**Comment by khmarbaise** [comment]
Should be done with #58
