### ISSUE TITLE
Any way to update to the next stable minor-release?

### ISSUE THREAD

**Issue by Moeth** [mojohaus/versions-maven-plugin#577]
I have for example the dependency
```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
```

with mvn -DallowMajorUpdates=false -DprocessParent=true versions:use-latest-versions

I want to go to org.slf4j:slf4j-api:jar:1.7.36, but it updates it always to 1.8.0-beta4

Is there any possibility to take only real releases?

**Comment by bmarwell** [comment]
Have you tried to set some of the allowXUpdates to `false`?

https://www.mojohaus.org/versions-maven-plugin/display-dependency-updates-mojo.html#allowIncrementalUpdates

**Comment by slawekjaranowski** [comment]
You can use `rules.xml` for ignoring some of versions ...
https://www.mojohaus.org/versions-maven-plugin/version-rules.html

**Comment by Moeth** [comment]
> Have you tried to set some of the allowXUpdates to false?
>https://www.mojohaus.org/versions-maven-plugin/display-dependency-updates-mojo.html#allowIncrementalUpdates

Yes. But without any solution.

> You can use rules.xml for ignoring some of versions ...
> https://www.mojohaus.org/versions-maven-plugin/version-rules.html

Thanks a lot - that worked for me

```
mvn -U -DallowMajorUpdates=false -DprocessParent=true -Dmaven.version.rules=file:/<path>/rules.xml versions:use-latest-versions

<ruleset comparisonMethod="maven"
         xmlns="http://mojo.codehaus.org/versions-maven-plugin/rule/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://mojo.codehaus.org/versions-maven-plugin/rule/2.0.0 https://www.mojohaus.org/versions-maven-plugin/xsd/rule-2.0.0.xsd">
    <ignoreVersions>
        <ignoreVersion type="regex">.*-.*</ignoreVersion>
    </ignoreVersions>
</ruleset>
```
