### ISSUE TITLE
update-properties does not work across parent-child pom

### ISSUE THREAD

**Issue by prodj17** [mojohaus/versions-maven-plugin#582]
Version 2.8.1 and above

Parent POM has

```
<properties>
  <version.lib>1.0.0</version.lib>
</properties>

  <dependencies>
    <dependency>
      <groupId>org.example</groupId>
      <artifactId>someLib</artifactId>
      <version>${version.lib}</version>
    </dependency>
  <dependencies>
```
Child POM has

```
<properties>
  <version.lib>1.1.0</version.lib>
</properties>
```
The child $version.lib property is active (i.e. does control the version of someLib in use) however update-properties does not update $version.lib to latest version when run on the child POM. They will do this if the dependency on someLib exists in the child pom.

**Comment by prodj17** [comment]
@slawekjaranowski Do you have a estimate when this change will be released(when is the next release cycle)?

**Comment by slawekjaranowski** [comment]
We don't have a release cycle, and estimations.

You can drop a line o dev list.

**Comment by prodj17** [comment]
Hi, @stefanseifert I've seen you did the last three releases of this plugin. Are you planning to do a new release soon? My team is really looking forward for this issue to go live,
