### ISSUE TITLE
dependency-updates-report: limit to only artifacts that have updates and are in the dependency graph

### ISSUE THREAD

**Issue by jdavis4452** [mojohaus/versions-maven-plugin#589]
I am curious if it can be possible to limit this report to only show dependencies that have updates and only show dependencies that are in the dependency graph?

We have a dependency mgmt pom that is shared across our assemblies and currently the report shows all the imported dependencies. So it shows more than what is in the dependency graph for the assembly.

I tried setting \<processDependencyManagementTransitive\>false\</processDependencyManagementTransitive\>. That doesn't give me what I want though because it also gets rid of all the imported dependencies. Some of these are in the dependency graph and we want to see those in the report, we just want to exclude those that aren't in the dependency graph for the assembly.  I think we need a setting to exclude dependencies that aren't in the dependency graph.

Also it would be nice if it would only show the dependencies that have updates
For example:
![image](https://user-images.githubusercontent.com/4868928/168088955-d2f30036-512a-4a32-9ab4-5411a4d7cf8a.png)
It would be nice if there was a setting to exclude dependencies that don't have updates.

**Comment by ajarmoniuk** [comment]
I'll gladly take it up.
