### ISSUE TITLE
Getting current version?

### ISSUE THREAD

**Issue by davidnoblevpa** [mojohaus/versions-maven-plugin#59]
Is there a command just to retrieve the current version of the project?  I cannot seem to find this anywhere...

**Comment by prostagma** [comment]
Did you read the docs? Take a look at [this,](http://www.mojohaus.org/versions-maven-plugin/set-mojo.html) there is the set goal, you can use it like this: 
`mvn versions:set -DnewVersion=2.0-SNAPSHOT`

**Comment by prostagma** [comment]
I think there isn't. On the most cases that I needed a functionality like this, I've just read the project's version from the xml, throught an ant script, or somethis so.

**Comment by averigin** [comment]
There's nothing like that built in to the versions plugin.

There is a relevant question on [StackOverflow](http://stackoverflow.com/q/3545292/800579) which suggests several ways you can use the [exec-maven-plugin](http://www.mojohaus.org/exec-maven-plugin/) to accomplish this.

The [solution](http://stackoverflow.com/a/26514030/800579) I typically use is:
`mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}'  --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`

**Comment by khmarbaise** [comment]
Something like this:

    mvn help:evaluate -Dexpression=project.version

is too simple?

**Comment by davidnoblevpa** [comment]
I want to be able to store the result as a bash variable, so that dumps out too much output.  I just assumed some such feature would be available in the "versions" plugin, seeing as you can change/update them, why not share what it is before updating?

The the solution I have been using is the same as mentioned above:
`mvn -q \
  -Dexec.executable="echo" \
  -Dexec.args='${project.version}' \
  --non-recursive \
  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`

**Comment by khmarbaise** [comment]
What do you mean by `seeing as you can change/update them, why not share what it is before updating?` ?

**Comment by khmarbaise** [comment]
Unfortunately no feedback
