### ISSUE TITLE
Always update outputTimestamp

### ISSUE THREAD

**Issue by qoomon** [mojohaus/versions-maven-plugin#595]
**Current Behaviour**
`outputTimestamp` value is only updated if `versions:set` has changed version value

**Expected Behaviour**
`outputTimestamp` value should be updated always if `versions:set` is executed or at least for `-SNAPSHOT` versions.

**Comment by slawekjaranowski** [comment]
Maybe new parameters with values:
- never
- always
- onchange

For SNAPSHOT I don't see benefit - in standard way project is always in snapshot version

**Comment by qoomon** [comment]
A parameter would be awesome, however what's the disadvantage in always setting outputTimestamp?

**Comment by slawekjaranowski** [comment]
In standard situation when nothing is changed also `outputTimestamp` should not be changed. 
So my proposition is to add flags to preserve current behavior.

**Comment by qoomon** [comment]
sound reasonable

**Comment by qoomon** [comment]
thx
