### ISSUE TITLE
versions:display-dependency-updates add support for excludes parameter

### ISSUE THREAD

**Issue by skin27** [mojohaus/versions-maven-plugin#620]
I like to use the excludes parameter with the versions:display-dependency-updates goal. Idea is to exclude certain dependencies (by groupid / artifactid / version) from displaying with the excludes parameter like for example in use-latest-versions (https://www.mojohaus.org/versions-maven-plugin/use-latest-versions-mojo.html).

**Comment by Dankur96** [comment]
There is already a PR for that case: https://github.com/mojohaus/versions-maven-plugin/pull/602

**Comment by skin27** [comment]
Sorry, I missed that. +1 for that issue then.
