### ISSUE TITLE
Cannot resolve parent POM

### ISSUE THREAD

**Issue by prostagma** [mojohaus/versions-maven-plugin#63]
Using the commandline:
`mvn -P run-its`

Stacktrace:

> [INFO] Scanning for projects...
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
> [ERROR]   The project org.codehaus.mojo:versions-maven-plugin:2.3-SNAPSHOT (/home/fabio/workspace/versions-maven-plugin/pom.xml) has 1 error
> [ERROR]     Non-resolvable parent POM: Could not find artifact org.codehaus.mojo:mojo-parent:pom:39-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
>

**Comment by khmarbaise** [comment]
Yes it's ok cause currently a VOTE for new version of mojo-parent is running which is not yet finished...which will result in version 39 of mojo-parent....
