### ISSUE TITLE
Getting valid versions comparison in case of qualifiers (alpha, beta, milestone, rc) 

### ISSUE THREAD

**Issue by sultan** [mojohaus/versions-maven-plugin#632]
![image](https://user-images.githubusercontent.com/5782559/184096019-377aadb5-06b2-418a-b84d-8d2d39d38c34.png)
![image](https://user-images.githubusercontent.com/5782559/184096088-710930cb-4ebb-4cb3-b64d-bbdac2c93539.png)

In this exemple, we can se how RC versions are treated differently from non RC versions, however Activation APIs are from same 2.0 Major and should be treated as such

**Comment by sultan** [comment]
example of actual problem :

v3.0, searching next minor, creating upper and lower bounds
upper bound included v3.1
lower bound excluded v4.0

however versions v4.0 with qualifiers alpha, beta, rc lies before 4.0, this is an expected normal feature !

the problem is 4.0rc lies between 3.1 and 4.0 excluded
then the problem are the bounds creation that is not well designed

the bounds created should be 3.1snapshot and 4.0snapshot

![image](https://user-images.githubusercontent.com/5782559/188847011-aa41c4dc-2e02-4fae-9aba-b5d6c3152f2b.png)

**Comment by sultan** [comment]
Regression: bug is back after infinity calculus.

**Comment by sultan** [comment]
![image](https://user-images.githubusercontent.com/5782559/195997748-fe02407c-a2ff-46ad-b55c-ba886e8c3638.png)

**Comment by sultan** [comment]
non release versions are now ignored

**Comment by sultan** [comment]
![image](https://user-images.githubusercontent.com/5782559/195997834-0c6b4f13-ef5a-4594-b0b8-33e50c0999c0.png)

**Comment by sultan** [comment]
this leads to contradictory reports : 
![image](https://user-images.githubusercontent.com/5782559/195997874-c02ee379-592e-4b36-8dae-f99d3f52c059.png)

**Comment by ajarmoniuk** [comment]
Created #760
