### ISSUE TITLE
display-dependency-updates not resolving to correct version

### ISSUE THREAD

**Issue by c3auer** [mojohaus/versions-maven-plugin#638]
Example output:
[INFO]   commons-beanutils:commons-beanutils ......... 1.9.4 -> 20030211.134440
[INFO]   commons-codec:commons-codec .................. **1.12 -> 20041127.091804**
[INFO]   commons-io:commons-io ...................... 2.11.0 -> 20030203.000550
[INFO]   commons-net:commons-net ....................... 3.3 -> 20030805.205232

Occurs if conventional versioning is not used for a given library.  Example for commons-codec, version 20041127.091804 was from 24-Nov-2005.  Latest version is actually 1.15 from 1-Sep-2020.

**Comment by slawekjaranowski** [comment]
unfortunately versions like: `20041127.091804` are correct Maven version, both items separated by dot are numbers ...

when we compare numbers that is true:

```
20041127 > 1
``` 

The same effect:
https://search.maven.org/search?q=g:commons-codec%20AND%20a:commons-codec

Of course conventional versioning is broken in this example ...

`versions-m-p` and `Maven` compare versions by numbers not by date of release.

**Comment by pzygielo** [comment]
I believe - once artifacts with changed versioning scheme are determined, [Ignoring certain versions](https://www.mojohaus.org/versions-maven-plugin/version-rules.html) can be used to solve such problem.
IMO this is not an issue to be solved here.

**Comment by slawekjaranowski** [comment]
agree it is not a bug in versions-m-p

**Comment by Marcono1234** [comment]
Can this plugin access / determine the release date of artifacts? In that case, even though the versioning of the projects is incorrect, the versions-maven-plugin could possibly first search for versions released after the current one (based on the release date) and only then compare the version numbers.
