### ISSUE TITLE
Upcoming next release - 2.12.0

### ISSUE THREAD

**Issue by slawekjaranowski** [mojohaus/versions-maven-plugin#645]
I'm going to release next version `2.12.0` in a few days.

Please help with:
 - review existing issues - may be some is easy to fix and there is willing for it
 - review existing PR - may be some can be merged

Changes in upcoming release:
https://github.com/mojohaus/versions-maven-plugin/compare/versions-maven-plugin-2.11.0...refs/heads/master

**Comment by ajarmoniuk** [comment]
Please review the PR for #648

**Comment by slawekjaranowski** [comment]
@ajarmoniuk please let me know when I can do release. 
Do you want add something more?

**Comment by ajarmoniuk** [comment]
I've just begun working on #213, but I think it could take a couple of days (one or two).

**Comment by ajarmoniuk** [comment]
I'm almost done with #231 which I consider a bug (I don't think it was intentional to allow downgrading), but I've added a feature to allow it and fixed the behaviour somehow (it did not work at all for ranges).

**Comment by slawekjaranowski** [comment]
I'm very glad to next release, we have many bug fixes and improvements. 

Of course I want not to wait to resolve all opened issues.

So next release will be at **5 of September**.
Unless you discover some of critical issue.

Big thanks to @ajarmoniuk

**Comment by slawekjaranowski** [comment]
Done.
