### ISSUE TITLE
Version specified in invoker integration test is not updated by `versions:set`

### ISSUE THREAD

**Issue by jaxzin** [mojohaus/versions-maven-plugin#67]
I have a team pom project that have a maven-invoker-plugin integration test to validate it. We also build and test pull requests with unique maven versions by running `mvn versions:set -DnewVersion=x.y.z-pr-$PULL_REQUEST-SNAPSHOT` before each build of a pull request.  In this case the test fails because the pom of the invoker test isn't updated with the correct parent pom.

```
pom.xml <-- updated correctly with com.example:myexample:1.0-pr-123-SNAPSHOT
src/
   it/
     simple-it/
        pom.xml <-- needs to be updated with a parent of com.example:myexample:1.0-pr-123-SNAPSHOT
```

**Comment by khmarbaise** [comment]
Can you show a little real example of the problem...cause i assume you don't use the invoker correctly... Do you use `@project.version@` in your invoker pom.xml file?

**Comment by jaxzin** [comment]
That's exactly what I was missing. I wasn't aware `@project.version@` was available. Switched my integration tests to use that rather than hard-code the version and I'm good now.
