### ISSUE TITLE
Enhancement: BaseMojoTestCase should initialise @parameter properties with default values

### ISSUE THREAD

**Issue by ajarmoniuk** [mojohaus/versions-maven-plugin#676]
Currently this is not being done, as a consequence, test writers must care to initialise test values manually. I think this could be automated, for example using reflection.

**Comment by slawekjaranowski** [comment]
IMHO should be done in testing library for plugins

**Comment by ajarmoniuk** [comment]
Maven testing harness?

**Comment by ajarmoniuk** [comment]
-> Create a ticket there + implement it

**Comment by slawekjaranowski** [comment]
https://issues.apache.org/jira/projects/MPLUGINTESTING/
https://github.com/apache/maven-plugin-testing

the latest release 2014 😄
