### ISSUE TITLE
2.12.0 - allowSnapshots don't find last snapshot with plugin version 2.12.0

### ISSUE THREAD

**Issue by ndaussy** [mojohaus/versions-maven-plugin#690]
Hello,

Since last release (2.12.0) few day ago, update-parent goal don't find last snapshot push.
`mvn version:update-parent  "DparentVersion=[0,2.76-SNAPSHOT]" -DallowSnapshots=true -U`

We force to use 2.11.0 and plugin found last snapshot version.
`mvn org.codehaus.mojo:version-maven-plugin:2.11.0:update-parent  "DparentVersion=[0,2.76-SNAPSHOT]" -DallowSnapshots=true -U`

Something have change with allowSnapshots to allow him to check snapshot version ?

**Comment by ajarmoniuk** [comment]
Looking into it.

**Comment by ajarmoniuk** [comment]
Similar to #670, fixed by PR #671 

Verified by:

1) maven on `versions-maven-plugin`:

```sh
mvn org.codehaus.mojo:versions-maven-plugin:2.12.1-SNAPSHOT:update-parent -DallowSnapshots=true "-DparentVersion=[0,71-SNAPSHOT]"
```

2) created an it with a test similar to above

3) created a unit test:

```java
    @Test
    public void testShouldUpgradeToSnapshot() throws MojoExecutionException, XMLStreamException, MojoFailureException
    {
        mojo.getProject().setParent( new MavenProject()
        {{
            setGroupId( "default-group" );
            setArtifactId( "parent-artifact" );
            setVersion( "0.9.0" );
        }} );
        mojo.allowSnapshots = true;
        mojo.parentVersion = "[0,1.0.1-SNAPSHOT]";
        try ( MockedStatic<PomHelper> pomHelper = mockStatic( PomHelper.class ) )
        {
            pomHelper.when( () -> PomHelper.setProjectParentVersion( any(), any() ) ).thenReturn( true );
            mojo.update( null );
        }
        assertThat( changeRecorder.getChanges(),
                hasItem( new VersionChange( "default-group", "parent-artifact", "0.9.0",
                        "1.0.1-SNAPSHOT" ) ) );
    }
```

Appears to be fixed.

**Comment by ajarmoniuk** [comment]
@slawekjaranowski should I add this unit test to the suite (will slow down compilation ever so slightly ;) )

**Comment by slachiewicz** [comment]
yes, please open PR
