### ISSUE TITLE
Version 2.12.0 is not able to read resolver-status.properties

### ISSUE THREAD

**Issue by KMikkey** [mojohaus/versions-maven-plugin#691]
After the upgrade to version 2.12.0 we had an error 
`Not updating version: could not resolve any versions `
in details after using -X option in mvn command.
`Proposal is to update from 2.2.0-SNAPSHOT to null`
Plugin was searching for required pom.xml only on central repository but when not found
`[DEBUG] Skipped unreadable resolution tracking file /root/.m2/repository/com/heiler/ppm/aldi/com.heiler.ppm.aldi.root/resolver-status.properties`
After revert to version 2.11.0 all is working correct but with one error
`[DEBUG] Error releasing shared lock for resolution tracking file: /root/.m2/repository/...//resolver-status.properties`

**Comment by ajarmoniuk** [comment]
Could you please attach the full (obfuscated if you wish) output of the -X invocation, and  preferably provide a test pom.xml which reproduces the issue? If you invoked the plugin from command line, please also provide invocation arguments.
