### ISSUE TITLE
problems replacing 1.0.0-SNAPSHOT property for 1.0.0-M23

### ISSUE THREAD

**Issue by fphilip** [mojohaus/versions-maven-plugin#7]
It is possible replace SNAPSHOTS?

![candidate](https://cloud.githubusercontent.com/assets/2574152/8722053/0c371ef2-2bc1-11e5-8a06-4d9e47fc67d0.png)

**Comment by khmarbaise** [comment]
Can you make an example project which shows the wrong behaviour.....
