### ISSUE TITLE
Plugin uses the reserved maven prefix "maven."

### ISSUE THREAD

**Issue by ajarmoniuk** [mojohaus/versions-maven-plugin#717]
As noted in #454, versions-maven-plugin should not be using the `maven` property prefix. Hereby changing this to `mojohaus.versions`, as agreed there. 

This is a breaking change.

**Comment by pzygielo** [comment]
- https://github.com/mojohaus/versions-maven-plugin/pull/718

**Comment by pzygielo** [comment]
- https://github.com/mojohaus/versions-maven-plugin/pull/724

**Comment by daniel-beck** [comment]
Probably more accurate to call it _reserved_?

**Comment by slawekjaranowski** [comment]
For me `versions.` as prefix will be ok.

As such changes are not compatible, I would see one property per one PR with title like `Rename property xxx to yyy`

I would to show those change in clear way in release notes.

**Comment by ajarmoniuk** [comment]
> I would to show those change in clear way in release notes.

Should I update something?

**Comment by slawekjaranowski** [comment]
I would like to review it and discus more ....

I agree that properties begins from `maven.` should be not used.

What I see:
- in project most of properties are not prefixed  
- if prefix is used it is `versions` - not `version` ( at most case ) 

To think about:
- whether to use a prefix at all
- if property is dedicated for cli maybe without prefix is better ... i'm layzy
- whether all `Mojo Parameters` need property?

**Comment by ajarmoniuk** [comment]
My thoughts

- prefixes makes sense if the plugin is used in combination with other plugins
- currently this is difficult to imagine, but let's say we introduce a feature that would work in combination with the enforcer plugin, i.e. conditions for failure
- I don't think all pom.xml properties need a user property, but it makes it much easier to test the plugin using options passed via invoker.properties
- long property names make the possibility of collisions (with other plugins) less likely, but they can of course still occur
- if property is dedicated for cli maybe without prefix is better ... i'm layzy -> let's just use 'versions' for short/collision prone property names
