### ISSUE TITLE
Request for patch release of versions-maven-plugin

### ISSUE THREAD

**Issue by nasokan** [mojohaus/versions-maven-plugin#736]
Hello - is there a possibility of a release that includes `maven-common-artifact-filters@3.3.2` ? This version of `maven-common-artifact-filters` includes a [fix](https://github.com/apache/maven-common-artifact-filters/commit/500569dad88b8f91e77116a2743a4685c920bed5) that can gracefully handle cases when there are no pattern matches. 

### Sample command
```
mvn versions:use-dep-version -DdepVersion=1.0.1 '-Dincludes=com.example:module::*-SNAPSHOT'
```
pom.xml
```
<dependency>
    <groupId>com.example</groupId>
    <artifactId>module</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Expected:** 
Version remains unchanged
**Actual:**
Fails with NullPointerException

**Comment by slawekjaranowski** [comment]
You can try override dependencies for plugin as workaround, like:
```
<plugin>
  <artifactId>versions-maven-plugin</artifactId>
  ....
    <dependencies>
       <dependency>
              <groupId>org.apache.maven.shared</groupId>
              <artifactId>maven-common-artifact-filters</artifactId>
              <version>3.3.2</version>
        </dependency>
   </dependencies>
<plugin>

```

**Comment by slawekjaranowski** [comment]
@nasokan Please follow #742
