### ISSUE TITLE
Upcoming next release - 2.13.0

### ISSUE THREAD

**Issue by slawekjaranowski** [mojohaus/versions-maven-plugin#742]
We have next pack of great changes. 

I think we can release next version to allow receive new feedback.
I have plan to release about 15-16 of October

List of issues and PRs:
https://github.com/mojohaus/versions-maven-plugin/issues?q=milestone%3A2.13.0

Detailed changes:
https://github.com/mojohaus/versions-maven-plugin/compare/versions-maven-plugin-2.12.0...master

**Comment by slawekjaranowski** [comment]
@ajarmoniuk, @sultan I see that you work one many issues - I want to plan next releases, so:
 
- please links issues, PR that should be included 
- which should be postponed to next releases

Finally ping me when you will be ready.

When I see how many changes we have last time, I'm for frequent release, even once per month. 
It will be easier to get more feedback from users.

**Comment by ajarmoniuk** [comment]
@slawekjaranowski 

The following pull requests seem to cause problems:
- #733 
- #753 

They are both linked to issue #454 

I'm not sure whether I will be able to fix this, so you might want to pull those from the release.

**Comment by sultan** [comment]
Current PR not ready and can wait the next train. (#732 is linked with #730 which is not ready,)

**Comment by ajarmoniuk** [comment]
I'm almost done... I'll ping you when the fix is ready.

**Comment by ajarmoniuk** [comment]
@slawekjaranowski 

If all is good, it looks like:
- issue #454: PR #733 and PR #753
can both be included on condition that PR #761 (fixing #760) is also included

- PR #759 (issue #367) can be included
- PR #757 (issues #754 and #755)
- PR #756 should be closed unmerged
- PR #717 -- nice to have

**Comment by sultan** [comment]
#763 / #762 Fixes issues in the Plugin HTML Report, nice to have with @ajarmoniuk's #760

**Comment by slawekjaranowski** [comment]
And one proposition from me: 
- #764

**Comment by sultan** [comment]
currently rebasing my PR onto @ajarmoniuk job

**Comment by sultan** [comment]
Reports fixing
* PR #763 
Nice to have
* PR #732

**Comment by ajarmoniuk** [comment]
@slawekjaranowski 

#777 contains an important bug fix

**Comment by slawekjaranowski** [comment]
I hope we are ready ... 😄 

I will release tomorrow after once again checking especially site output

**Comment by sultan** [comment]
maybe PR #771 ?

**Comment by slawekjaranowski** [comment]
Released ... now waiting for feedback 😄

**Comment by ajarmoniuk** [comment]
Maybe we need to increase test coverage 😂

**Comment by robert-gdv** [comment]
Thank you for that release! It fixed also an allowMajorUpdates=false issue in update-parent goal, which resulted in an update of spring-boot-starter-parent from 2.7.5 to 3.0.0 instead of 2.7.6.

Unfortunately, spring-boot-dependencies-2.7.5 defines the version for this plugin to be 2.10.0. Therefore you have to specify explicitly the plugin version if you don't want to run into a major version update.
`mvn -DallowMajorUpdates=false org.codehaus.mojo:versions-maven-plugin:2.13.0:update-parent`
