### ISSUE TITLE
artifactId cant include property

### ISSUE THREAD

**Issue by stefanmeisner** [mojohaus/versions-maven-plugin#76]
The plugin cant handle an artifactId like my.artifact.${somProperty}.
Both the jar and deploy plugins handles artifactId like this.

**Comment by khmarbaise** [comment]
What about providing a pull request ?

**Comment by erikvanoosten** [comment]
This little toy project can be used to play with the problem.
[versions-showcase.zip](https://github.com/mojohaus/versions-maven-plugin/files/619414/versions-showcase.zip) (zip-file 1Kb containing 2 pom files.)

For example, when you invoke
```
mvn -U org.codehaus.mojo:versions-maven-plugin:2.3:update-parent \
        org.codehaus.mojo:versions-maven-plugin:2.3:use-latest-releases \
        org.codehaus.mojo:versions-maven-plugin:2.3:update-properties \
        org.codehaus.mojo:versions-maven-plugin:2.3:commit
```

inside the project, I expect the dependency to scalatest to be updated. Currently it is not.
