### ISSUE TITLE
Regression: updates incorrectly reported in report overview

### ISSUE THREAD

**Issue by ajarmoniuk** [mojohaus/versions-maven-plugin#760]
```java
    @Test
    public void testWrongReportBounds() throws IOException, MavenReportException
    {
        OutputStream os = new ByteArrayOutputStream();
        SinkFactory sinkFactory = new Xhtml5SinkFactory();
        new TestDependencyUpdatesReportMojo()
                .withOnlyUpgradable( true )
                .withDependencies(
                        dependencyOf( "test-artifact" ) )
                .withArtifactMetadataSource( mockArtifactMetadataSource(new HashMap<String, String[]>()
                {{
                   put( "test-artifact", new String[] { "1.0.0", "2.0.0-rc2" } );
                }} ) )
                .generate( sinkFactory.createSink( os ), sinkFactory, Locale.getDefault() );

        String output = os.toString().replaceAll( "\\s*", "" );
        assertThat( output, allOf(
                containsString( "<td>report.overview.numNewerMajorAvailable</td><td>1</td>" ),
                containsString( "<td>report.overview.numUpToDate</td><td>0</td>" ) ) );
    }
```

For a project containing a non-release update, no updates are reported, but the update (2.0.0-rc2) will still be listed in updates.

**Comment by ajarmoniuk** [comment]
The root cause is the fact that I was only adding "-snapshot" in incrementSegment to snapshot versions. This was initially done (before this "infinity calculus") because "-snapshot" is treated as the lowest possible version, lower than the release, which acts as a pseudo "minus infinity".

Well, I could either do that or introduce a real "minus infinity".

**Comment by sultan** [comment]
i would agree with this, even -1 is ok
we could use -1 in the int fields of the artifact version then 2.(-1) < 2.0,
any risks of unexpected results with strings though?

**Comment by ajarmoniuk** [comment]
> i would agree with this, even -1 is ok we could use -1 in the int fields of the artifact version then 2.(-1) < 2.0, any risks of unexpected results with strings though?

No, that won't work -- ComparableVersion won't treat it correctly. But I'm almost done.
