### ISSUE TITLE
NullPointerException if groupId is missing

### ISSUE THREAD

**Issue by m12n** [mojohaus/versions-maven-plugin#77]
When using a parent POM, the `groupId` can be omitted. In this case, the `versions:set` goal fails with a `NullPointerException` at org.codehaus.mojo.versions.api.PomHelper.getModelEntry(PomHelper.java:1571).

```
1571            if ( groupId.equals( getGroupId( model ) ) && artifactId.equals( getArtifactId( model ) ) ) 
1572            {
1573                return entry;
1574            }
```

The pom.xml looks like this:

```
  <modelVersion>4.0.0</modelVersion>
  <artifactId>my-artifact</artifactId>
  <version>1.0-SNAPSHOT</version>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>parent</artifactId>
    <version>1.0</version>
  </parent>
```

**Comment by prostagma** [comment]
Can you give a command line call example to simulate the problem?

**Comment by m12n** [comment]
This is an example that demonstrates the problem: https://github.com/m12n/example-mvn-versions-bug

**Comment by prostagma** [comment]
I could simulate the bug on the 2.2 version of the plugin, but not in the 2.3. Probably the bug is already fixed :+1:

**Comment by khmarbaise** [comment]
Version 2.3 is not yet released ? I assume you mean current master here in github ?

**Comment by prostagma** [comment]
Yes, I couldn't simulate the error on the current master branch of the plugin.

**Comment by khmarbaise** [comment]
I will close this issue based on the reported behaviour against current master.
