### ISSUE TITLE
onlyUpgradable does not work for dependency-updates-report

### ISSUE THREAD

**Issue by TorstenKruse** [mojohaus/versions-maven-plugin#776]
Hi.
I use: mvn versions:dependency-updates-report -DonlyUpgradable=true

But the dependency-updates-report.html still contains dependencies with a green checkbox indicating that this dependency is still on the latest version.

Is this a bug or am I missing something?

**Comment by ajarmoniuk** [comment]
Thanks for the report, it looks like there's indeed an issue. Let me fix it.

**Comment by TorstenKruse** [comment]
Great support! Thanks a lot.
