### ISSUE TITLE
Any way to set SNAPSHOT dependency backward to release?

### ISSUE THREAD

**Issue by ingyhere** [mojohaus/versions-maven-plugin#78]
We have contributors who prematurely set the versions of dependencies (that will go untagged because there are no changes) to SNAPSHOTS. I would like the versions plugin to look behind and get the last release. I cannot get any of the goals to perform this task. Is there any way to do this?

If there is not, I will either fork or write my own custom implementation to do a "release-before" goal.

**Comment by DiJu519** [comment]
I am in the same boat.

I build as a release and then flip my dependencies back to snapshot in preparation of the next release, and to facilitate any change that's checked in.

My issue is, i currently am forced to rebuild my dependencies as release because the versions plugin won't let me do "get latest release ignoring current version". Instead i'm forced to always look forward.

It'd be nice to be able to specify "get me latest release but lock the Major Minor"

**Comment by khmarbaise** [comment]
Can you give me an example how your project look like ? Is that a multi module build ? Or do you have external dependencies which you turn back to SNAPSHOT`s ?

**Comment by DiJu519** [comment]
Each Component consists of a multi module build[all versioned the same]. And i have Components which Depend on Components. 

In terms of implementation. A little bit similar to what http://www.mojohaus.org/versions-maven-plugin/force-releases-mojo.html would do (e.g be able to go from 3.4.5-SNAPSHOT to 3.4.4). Ideally i'd have the granularity to say "restrict Major, Minor or Patch".

That might not be a clear explanation please let me know if i can be more elaborate.

**Comment by khmarbaise** [comment]
If I correctly understand this is already fixed with #98...

**Comment by DiJu519** [comment]
Oh nice!

Seems it's fixed for the update-properties goal, but not the use-latest-releases or use-latest-snapshots or use-latest-versions goals. Atleast according to the last time i looked at the documentation.....

**Comment by DiJu519** [comment]
Wow looking now i don't even see -DallowDowngrade here

http://www.mojohaus.org/versions-maven-plugin/update-properties-mojo.html

How out of date is this documentation?

**Comment by khmarbaise** [comment]
The documentation represents the state of the current available public release...so the point is that the current master has not yet been released to the public...

**Comment by khmarbaise** [comment]
Hi, so versions-maven-plugin release 2.4 is out. This should be fixed now. If not please don't hesitate to reopen this issue...
