### ISSUE TITLE
Set goal with newVersion and oldVersion arguments specified fails to update only the versions which matches the oldVersion and updates all the versions

### ISSUE THREAD

**Issue by soselamet** [mojohaus/versions-maven-plugin#794]
Set goal with newVersion and oldVersion arguments specified fails to update only the versions which matches the oldVersion and updates all the versions.

Example :
command line / mvn versions:set -DnewVersion="TEST" -DoldVersion="TEST2"

Sample maven execution output log lines : 

[INFO] Processing change of com.some.obscure.company.someniftymodule-parent:TEST2 -> TEST
.
.
.
[INFO]     Updating project com.some.obscure.company.someniftymodule-document-parent
[INFO]         from version 0.101.1-SNAPSHOT to TEST

Possible Solution :
Please see the diff file in the zip archive below for the possible fix.

[oldVersion_fix.zip](https://github.com/mojohaus/versions-maven-plugin/files/9862054/oldVersion_fix.zip)

**Comment by ajarmoniuk** [comment]
Would you like to make a PR with your changes?

**Comment by ajarmoniuk** [comment]
I'm unable to reproduce the issue you're reporting. Could you attach a sample project to reproduce it? Also, could you please state the version of the plugin you're working with?

**Comment by ajarmoniuk** [comment]
I was able to reproduce the issue.

It does not occur if the artifact with the given oldVersion is found in the reactor.

Strangely, if the artifact with the given version is *not* found, then the root model is changed anyway! I don't understand the reason for it, need to see *why* this has been done like that. Obviously, as mentioned earlier, your change breaks a few tests. It could have also been done earlier in the stack, in the main method (execute).

However, we're dealing with an old code, and, as I said, I need to undestand the reason it's been done like that first 😆

**Comment by soselamet** [comment]
Thank you for taking this issue in your focus.

The diff I shared was a quick and experimental snippet that was not intended to be a PR level contribution.

I guess integration tests are not executed as part of the regular maven install profile so I didn't observe any test failure. 😃

Please let me know if there is a need for direct contribution via a PR.
