### ISSUE TITLE
[Bug 2.3] Classifier not correctly supported in lock-snaphots

### ISSUE THREAD

**Issue by ghilainm** [mojohaus/versions-maven-plugin#80]
I have a dependency of the following form in the dependency management section of my BOM.
`<dependency>
                <groupId>a.b.c</groupId>
                <artifactId>my-artifact</artifactId>
                <version>2.1.3-SNAPSHOT</version>
                <classifier>resources</classifier>
                <type>tar.gz</type>
            </dependency>`

I then try to run the following maven command: 'mvn clean org.codehaus.mojo:versions-maven-plugin:2.3-SNAPSHOT:lock-snapshots'

I get an error when the plugin tries to contact the repository saying he cannot find the artifact. The artifact is however present in the repository.

EDIT: I get exactly the same error when it is a standard dependency.
[stack.txt](https://github.com/mojohaus/versions-maven-plugin/files/283691/stack.txt)

**Comment by khmarbaise** [comment]
Can you provide a full working example on github

**Comment by ghilainm** [comment]
Publish any artifact with a classifier in your local repository then try to lock snapshots you should get the error

**Comment by khmarbaise** [comment]
So checked with current master. Works now without any issue. I will not close it until I have a working integration test(s) for this....
