### ISSUE TITLE
Maintenance: versions-api

### ISSUE THREAD

**Issue by ajarmoniuk** [mojohaus/versions-maven-plugin#809]
Extract api to a separate module

**Comment by slawekjaranowski** [comment]
We should think what should be `versions-api`.

For me `versions-api` should have only interfaces for component which can be extended / implemented as extension for `versions-maven-plugin`, like `VersionComparator`.

I would like to have a project structure like:

- versions-api - public api for external extending plugin
- versions-maven-plugin - core plugin
- versions-report-maven-plugin - dedicated plugin for Maven site reports
- versions-common/internal - shared implementation used in plugin, report-plugin  - should be used only by versions project

**Comment by ajarmoniuk** [comment]
plus versions-enforcer

But I'd like to follow a more gradual approach for the time being, otherwise this will become a far too big of a PR

**Comment by slawekjaranowski** [comment]
> plus versions-enforcer
> 
> But I'd like to follow a more gradual approach for the time being, otherwise this will become a far too big of a PR

Yes, yes ... small steps.

**Comment by ajarmoniuk** [comment]
Currently there's no clear separation of the API and service implementation. I'd like to separate the API to a separate module as a next stage.
