### ISSUE TITLE
Webapp can't be updated after running the new version 2.13.0

### ISSUE THREAD

**Issue by MohamedSadiq102** [mojohaus/versions-maven-plugin#812]
When we run the old version 2.12.0 everything got updated-> mvn org.codehaus.mojo:versions-maven-plugin:2.12.0:set -DnewVersion="2.3.0_20221024_2231"

But the problem happens when we tried the new version 2.13.0 -> mvn org.codehaus.mojo:versions-maven-plugin:2.13.0:set -DnewVersion="2.3.0_20221024_2231"

The version in the pom.xml in the module webapp cannot be updated

**Comment by ajarmoniuk** [comment]
Please attach the full debug log and the pom.xml file(s).

To produce the debug log, you can use the -X option with maven.

**Comment by ajarmoniuk** [comment]
Let's close this one due to lack of information.

@slachiewicz please close
