### ISSUE TITLE
[Question] display-dependency-updates and change recorder

### ISSUE THREAD

**Issue by cmarchand** [mojohaus/versions-maven-plugin#821]
I'd like to produce a machine-readable changes file while using display-dependency-plugin, but nothing is written.

Here is the configuration I use :

```xml
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
        <version>2.13.0</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
	    <goals><goal>display-dependency-updates</goal></goals> 
	    <configuration>
              <changeRecorderFormat>xml</changeRecorderFormat>
              <outputFile>changes.log</outputFile>
              <dependencyIncludes>com.oxiane.formation.tools.oxslides:editor</dependencyIncludes>
              <processDependencyManagement>false</processDependencyManagement>
              <processPluginDependencies>false</processPluginDependencies>
              <processPluginDependenciesInPluginManagement>false</processPluginDependenciesInPluginManagement>
	    </configuration>
	  </execution>
	</executions>
      </plugin>
```

When running `mvn generate-sources` I expect a `versions-changes.xml` file being generated, but it is not.
Only the changes.log is generated

Please help me finding what I've missed...

Best regards,
Christophe

**Comment by slawekjaranowski** [comment]
You are right: https://github.com/mojohaus/versions-maven-plugin/pull/819#issuecomment-1321170978

Now only goals which change data in project generate ChangeRecord.
Goals `display-*` don't generate ChangeRecord events ...

**Comment by cmarchand** [comment]
So, leaving these properties `changeRecordFormat` and `changeRecordOutputFile` is counter intuitive and confusing...
As mentioned in [#819 (other comment)](https://github.com/mojohaus/versions-maven-plugin/pull/819#issuecomment-1321170978), they should be removed !

I'll apply a transfo once the log is generated.

Thanks for your response,
Christophe
