### ISSUE TITLE
[Bug 2.3] NullPointerException when they are no versions to update (setMojo)

### ISSUE THREAD

**Issue by ghilainm** [mojohaus/versions-maven-plugin#83]
The setMojo does not behave correctly when they are no versions to update.
I am launching it using the following command line:
`mvn -B -nsu org.codehaus.mojo:versions-maven-plugin:2.3-SNAPSHOT:set -DnewVersion=xxx -DgroupId=* -DartifactId=* -DoldVersion=* -DprocessParent=false -DprocessProject=true -DgenerateBackupPoms=false`

The version of the project is already xxx. Therefore they are no versions to update. This give me a NullPointerException on the following line of the setMojo class:
`current.getValue().setVersion( newVersion );`

**Comment by khmarbaise** [comment]
By `2.3` you mean the current state of the master ?

**Comment by ghilainm** [comment]
Yes ☺

**Comment by khmarbaise** [comment]
Ah ok..Thanks.

**Comment by ghilainm** [comment]
Where you able to reproduce?

**Comment by prostagma** [comment]
I could simulate the problem using exactly the same command line call as @ghilainm used.
The CLI call `mvn org.codehaus.mojo:versions-maven-plugin:2.3-SNAPSHOT:set -DnewVersion=xxx -DartifactId=*` also simulate the error.
