### ISSUE TITLE
groupID value specified by properties are not set

### ISSUE THREAD

**Issue by ahousing** [mojohaus/versions-maven-plugin#85]
We have a file that uses a property value for the groupId of a dependency.  This fails to resolve.  A simplified version is below (we actually define the property in our parent pom):

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>example.com</groupId>
    <artifactId>test</artifactId>
    <name>Test</name>
    <version>1.0.0</version>
    <properties>
        <test.groupId>foo</test.groupId>
    </properties>
    <dependencies>
        <dependency>
            <groupId>${test.groupId}</groupId>
            <artifactId>dependency</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>
```

```
$ mvn org.codehaus.mojo:versions-maven-plugin:set -q -DnewVersion=1.0.1 -DgenerateBackupPoms=false
expression: test.groupId no value
```

**Comment by ahousing** [comment]
Another similar pom file that would actually pass `mvn verify`:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>example.com</groupId>
    <artifactId>test</artifactId>
    <name>Test</name>
    <version>1.0.0</version>
    <properties>
        <test.groupId>org.codehaus.mojo</test.groupId>
    </properties>
    <dependencies>
        <dependency>
            <groupId>${test.groupId}</groupId>
            <artifactId>versions-maven-plugin</artifactId>
            <version>2.2</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by khmarbaise** [comment]
First a plugin should never be used as a dependency. Furthermore using a property for the groupId does from my point of view no sense. If you need having two different dependencies you have to create simply two projects with the different dependencies.

**Comment by ahousing** [comment]
The example with the plugin was just that, an example.  We don't actually use a plugin as a dependency.  As for whether using a property makes sense, we have a usecase for it.  (Being able to pick up a set of dependencies from one of two different groupId's, and making this change easily and quickly by just changing the property.)  Regardless, I would think that as long as it's a valid pom file that the versions-maven-plugin would want to support it... right?

**Comment by spacebel** [comment]
Sure using a property for groupId makes sense. I confirm the problem occurs, but not that in some cases the groupId property is resolved correctly !

**Comment by prostagma** [comment]
@ahousing and @spacebel, I couldn't simulate the issue. Can anyone post an example project that simulate the error on github?

**Comment by ahousing** [comment]
The two pom files above should reproduce the problem.  No need for a full-fledged project, right?  Did you try these two examples and fail?

**Comment by khmarbaise** [comment]
Can you make a full working project here on github so we or may be me can take a deeper look...

**Comment by aleksandr-m** [comment]
Looks same as #76.

**Comment by aleksandr-m** [comment]
@khmarbaise https://github.com/aleksandr-m/mcve-set-property

**Comment by fabiojb** [comment]
Maybe the issue #26 is related to this issue too.
