### ISSUE TITLE
lock-snapshots does not modify properties

### ISSUE THREAD

**Issue by WouterBanckenACA** [mojohaus/versions-maven-plugin#88]
I'm trying to use the maven-versions plugin to lock the SNAPSHOTs in my pom to their latest timestamped version. 

To do this, I first use the `update-properties` goal which sets all maven properties containing versions to their latest possible version. Secondly, I want to use the `lock-snapshots` goal to set the SNAPSHOT versions to their timestamped equivalent. 

However, the `lock-snapshots` goal only modifies the versions in the dependencies and dependencyManagement sections. Is there a way to modify the properties as well?

**Comment by victornoel** [comment]
@WouterBanckenACA why did you close this issue? do you have a solution to this problem?

**Comment by WouterBanckenACA** [comment]
I figured out that a property can be shared for multiple artifacts with slightly different timestamps (ms difference) so does not make sense to fix the property to a timestamped snapshot. (at least for my usecase)
