### ISSUE TITLE
Extend update-property behaviour to allow downgrade to version

### ISSUE THREAD

**Issue by schopbaf** [mojohaus/versions-maven-plugin#90]
We are using mvn in a product environment where we want to create products by cherry picking specific versions for the required artifacts. Therefore we need the possibility to downgrade to an earlier version of an artifact.

**Comment by khmarbaise** [comment]
What about providing a pull request ?

**Comment by schopbaf** [comment]
ok i will give it a go

**Comment by khmarbaise** [comment]
Has been integrated into with #53
