### ISSUE TITLE
Add ability to create XML report

### ISSUE THREAD

**Issue by sabaka** [mojohaus/versions-maven-plugin#93]
Hi,

It would be nice if plugin could create an XML report.
XML is easier to parse than HTML or console output. 
Ie: It would allow to use it on CIs in some script that could notify when one of hundred projects has new version of dependency. Also it would allow to use ignore lists for particular dependency on particular project in such scripts, b/c it's not always possible to update something due to broken API or some bugs.

If you can approve this feature I would implement it.

**Comment by khmarbaise** [comment]
See #42

**Comment by khmarbaise** [comment]
A pull request would be great...

**Comment by sabaka** [comment]
Hi.

I have draft for xml structure, could you take a look please?
```

	<summary>
		<usingLastVersion> </usingLastVersion>
		<nextVersionAlailable> </nextVersionAlailable>
		<nextIncremetalAvailable> </nextIncremetalAvailable>
		<nextMinorAvailable> </nextMinorAvailable>
		<nextMajorAvailable> </nextMajorAvailable>
	</summary>

	<dependencyManagements>
		<dependencyManagement>
			<groupId> </groupId>
			<artifactId> </artifactId>
			<scope> </scope>
			<classifier> </classifier>
			<type> </type>
			<currentVersion> </newestVersion>
			<nextVersion> </nextVersion>
			<nextIncremental> </nextIncremental>
			<nextMinor> </nextMinor>
			<nextMajor> </nextMajor>
			<status> </status>
		</dependencyManagement>
	</dependencyManagements>

	<dependencies>
		<dependency>
			<groupId> </groupId>
			<artifactId> </artifactId>
			<scope> </scope>
			<classifier> </classifier>
			<type> </type>
			<currentVersion> </newestVersion>
			<nextVersion> </nextVersion>
			<nextIncremental> </nextIncremental>
			<nextMinor> </nextMinor>
			<nextMajor> </nextMajor>
			<status> </status>
		</dependency>
	</dependencies>
```

And probably more fields will be included If I find anything useful in domain.
Very similar structure will be created for plugins.
Do we need XSD for XML?
PS: I will be on holidays next 2 weeks and I'm not sure I will be able to contribute until I'm back.

**Comment by khmarbaise** [comment]
Looks good so far...XML (may be via modello ?) No problem enjoy your holidays....

**Comment by sabaka** [comment]
Hi.
Sorry for delay.

I was trying to find out how to use modello to generate xml, but didn't find anything useful in google.
Maybe you have an example?

**Comment by khmarbaise** [comment]
@sabaka Would you be so nice to make a pull request against versions-maven-plugin project if you like?
