### ISSUE TITLE
Documentation of goal use-latest-versions parameters incorrect

### ISSUE THREAD

**Issue by Quest4Pc** [mojohaus/versions-maven-plugin#95]
The following page has incorrect information regarding the parameter "includesList"
http://www.mojohaus.org/versions-maven-plugin/use-latest-versions-mojo.html

When one attempts to use includesList on the command line it is ignored, the correct parameter is "includes"
http://stackoverflow.com/questions/17879183/maven-versions-ignored-includeslist

**Comment by PeterWippermann** [comment]
You could setup a Pull Request for this file:
https://github.com/mojohaus/versions-maven-plugin/blob/74fd75b93684ecd61435c3496957b75c2dac2f4d/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java#L53-L82

**Comment by khmarbaise** [comment]
It looks like you are mistaken the name of the parameter for the `pom.xml` and the one which can be used on command line. 
The one on command line is the one mentioned: `User property is: includes` and the one for the pom file is mentioned in the first column. In this case `includesList`.
