### ISSUE TITLE
Classpath-packaged rulesUri

### ISSUE THREAD

**Issue by benalexau** [mojohaus/versions-maven-plugin#97]
Organisations with many Maven projects often establish organisation-wide POMs which refer to organisation-wide resources JAR(s). Inside such resources JARs are configuration files needed by different Maven plugins, such as Checkstyle and PMD. This simplifies distribution of such configuration files, as they are simply managed (fetched, cached, versioned) as normal dependencies and can be added to the plugin's classpath scope for resolution.

The current `rulesUri` uses Wagon, which does not appear to support extracting the rule file from a classpath dependency. This means workarounds are needed such as `maven-dependency-plugin`'s `unpack` goal, or hosting the rules file on a server. It would be nice if failing to locate a given URL via Wagon would fall back to simply trying the classpath for the specified resource.

I am happy to submit a PR if this feature is desired.

**Comment by khmarbaise** [comment]
would be great if you offer a pull request for this....

**Comment by khmarbaise** [comment]
If you are interested in you can of course offer a pull request...

**Comment by khmarbaise** [comment]
Looks like no interest anymore. So I close the issue. If you have interest please reopen the issue.
