### ISSUE TITLE
Effect of update-properties has changed in v2.3

### ISSUE THREAD

**Issue by king-aegon** [mojohaus/versions-maven-plugin#98]
Previously (in v2.2), when running mvn version:update-properties, properties which were SNAPSHOT versions would not be updated to a released version unless a released version of equal version was available.

eg. running mvn versions:update-properties for property
`<myapp.version>4.7.0-SNAPSHOT</myapp.version>`
this property would only be updated if 4.7.0 had been released

Now (in v2.3) this has changed.  Running mvn version:update-properties is reverting all SNAPSHOT properties to the most recently released version regardless of the SNAPSHOT's version number.

In the example above, the myapp.version property is being changed to 4.6.2.

Is this change intentional?  The previous operation was much more suited to our needs.

**Comment by khmarbaise** [comment]
Have you tried to ue `-DallowSnapshots=false`? And yes there was a change #33

**Comment by king-aegon** [comment]
Using mvn versions:update-properties -DallowSnapshots=false on the example above results in the same thing -> it still updates 4.7.0-SNAPSHOT to 4.6.2

I only want the SNAPSHOT property to be updated once 4.7.0 is released.  Until then it should remain as 4.7.0-SNAPSHOT

**Comment by hSpille** [comment]
During development cycle it is not helpful when Mr. Jenkins is always reverting to an older release version of our module. So, we really want this "feature" to be reverted - or at least possible to be turned-off by arguments. 

Anyway - thx for developing versions-plugin: Nice work!!!11eleven

**Comment by binkley** [comment]
I'm getting related non-snapshot behavior as well.  Toggling between versions plugin 2.2 and 2.3, `update-properties` *downgrades* some plugins.  Affected plugins are those I manually bumped to latest version from what maven 3.3.9 specifies.  Version 2.2 does not have this behavior.

I refer to all plugin versions via properties.

**Comment by glianeric** [comment]
> Using mvn versions:update-properties -DallowSnapshots=false on the example above results in the same thing -> it still updates 4.7.0-SNAPSHOT to 4.6.2

Please use -DallowSnapshots=true

> I'm getting related non-snapshot behavior as well. Toggling between versions plugin 2.2 and 2.3, update-properties downgrades some plugins. Affected plugins are those I manually bumped to latest version from what maven 3.3.9 specifies. Version 2.2 does not have this behavior.

That's strange - the change #33 was a one-liner IIRC.

**Comment by glianeric** [comment]
Here's the change:

https://github.com/mojohaus/versions-maven-plugin/commit/733d60fa2f40626a3d39edba4b53f517aeba30d5

**Comment by king-aegon** [comment]
Hi glianeric

Given a property version of 4.7.0-SNAPSHOT, and there is no released version 4.7.0 or higher available, when using versions:update-properties -DallowSnapshots=false, I would expect the property to remain the same.

If 4.7.0 is subsequently released, the same command should update it to 4.7.0.  

This is what I expect to happen.  However, what is happening now is that before 4.7.0 is released, the command mvn:update-properties -DallowSnapshots=false, is downgrading the property to 4.6.2 -> I do not want it to do this.

You have suggested that I use -DallowSnapshots=true -> this would update the property to be 4.8.0-SNAPSHOT if it exists.  I do not want this to happen. 

**I only want the property to change if a newer released version is available.**

Brian

**Comment by glianeric** [comment]
I understand what you want, but you are relying on incorrect behavior IMHO.

Instead you should constrain the available versions using the versions plugin configuration, like so:

        <configuration>
          <properties>
            <property>
              <name>your_property_name</name>
              <version>[4.7.0-SNAPSHOT,4.8.0-SNAPSHOT)</version>
            </property>
          </properties>
        </configuration>

There is also a pull request for doing more or less what you are requesting - it updates x.y.z-SNAPSHOT specifically to x.y.z if I recall correctly.

**Comment by king-aegon** [comment]
I see this has been marked as fixed - what is the fix you have applied? The conversation history indicates that  you don't agree with what we have suggested -> what behaviour should we expect in version 3?

**Comment by khmarbaise** [comment]
It will behave as before 2.3 with the opportunity to be able to activate allowDowngrade explicitly...See my commit message of my commit.
