### ISSUE TITLE
Property based versions in managed dependencies are expanded to their values in v2.3

### ISSUE THREAD

**Issue by frank-van-eerden** [mojohaus/versions-maven-plugin#99]
We use property based versions in our managed dependencies, like:
`

```
<properties>
    <core.version>2.34.0-SNAPSHOT</core.version>
</properties>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.company.product</groupId>
            <artifactId>core-database</artifactId>
            <version>${core.version}</version>
        </dependency>
</dependencyManagement>`
```

We use the calls below to advance dependencies to their latest snapshot version:
       mvn versions:use-latest-versions -DgenerateBackupPoms=false -DexcludeReactor=false -DallowSnapshots=true -Dincludes=$componentVersionsToCheck -U
        mvn versions:update-properties -DgenerateBackupPoms=false -DexcludeReactor=false -DallowSnapshots=true -Dincludes=$componentVersionsToCheck -U

Since version 2.3 the properties are expanded to their values, resulting in 
`

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.company.product</groupId>
            <artifactId>core-database</artifactId>
            <version>2.34.0-SNAPSHOT</version>
        </dependency>
</dependencyManagement>`
```

Is there a reason for this change? It seems weird that ${} usage is replaced.

Regards, 
Frank van Eerden

**Comment by khmarbaise** [comment]
Unfortunately I can not reproduce this wrong behaviour but to be sure I have added some supplemental checks into the current IT's...So I close this issue. If you have further details please reopen this issue or a new one with a link to this one. Thanks for reporting.

**Comment by ghenkes** [comment]
@khmarbaise, I can reproduce using the pom below.

Versions 2.2
`mvn versions:use-latest-versions`: does nothing

Versions 2.3
`mvn versions:use-latest-versions`: 
```xml
updates <version>${guava.version}</version> to <version>21.0</version>
```

Note: with both versions, running `mvn versions:update-properties` updates correctly.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>thing</groupId>
    <artifactId>thing</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <guava.version>20.0</guava.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>2.3</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

**Comment by khmarbaise** [comment]
Ah now I see...The point is that by default `processDependencyManagement` and `processDependencies` are set to `true` which had been handled wrong in 2.2/2.1. In version 2.3 they have been handled correctly. So if you use:
```
mvn versions:use-latest-versions -DprocessDependencyManagement=false -DprocessDependencies=false
```
it will not change the dependency management and not the dependencies. The questions which results from that: May be I need to reconsider the default values for different goals...

**Comment by ghenkes** [comment]
Adding `-DprocessDependencyManagement=false` to the above example does result in the guava version not updating. But, if the guava version was set to 20.0 directly (rather than via the property), it also doesn't update, which is different than what happened in 2.2. I do still want to be able to run `use-latest-versions` to update dependencies that don't use a property for their version.

**Comment by ghenkes** [comment]
My guess is that this commit changed this behavior: https://github.com/mojohaus/versions-maven-plugin/commit/0f79ff0669d8ec8638dbfaab23056afd4d6ccb11
If I'm understanding things correctly, before we'd be getting an interpolated dependencyManagement section, which would have already had the versions extracted from the properties. Now with 2.3 we're getting the raw dependencyManagement section which does not have the properties injected.

**Comment by khmarbaise** [comment]
If I use versions-maven-plugin version 2.3 and use `mvn version:use-latest-versions` guava will be update to 21.0 while I have defined it directly instead of using a property....If you define `-DprocessDependencyManagement=false` than of course it will not being updated, cause you prevented that by setting the property...So in the end I don't see any issue here...

**Comment by ghenkes** [comment]
I've updated my example with a new dependency: maven-core

Versions 2.2
`mvn versions:use-latest-versions`:
guava stays `${guava.version}`
updates maven-core from `3.3.9` to `3.5.0-beta-1`

Versions 2.3
`mvn versions:use-latest-versions`:
updates guava from `${guava.version}` to `21.0`
updates maven-core from `3.3.9` to `3.5.0-beta-1`

`mvn versions:use-latest-versions -DprocessDependencyManagement=false`:
Nothing is updated.

Ultimately I want to replicate the functionality of 2.2, where `use-latest-versions` does update the version of dependencies which are not managed via properties, and does not touch those that are manage by properties, as those will by updated via `update-properties`. In the case of 2.3 either too much is updated or not enough.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>thing</groupId>
    <artifactId>thing</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <guava.version>20.0</guava.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.maven</groupId>
                <artifactId>maven-core</artifactId>
                <version>3.3.9</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>2.3</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

**Comment by heruan** [comment]
@khmarbaise I assume this issue is to be re-opened, am I right? I'm experiencing this problem, too.

**Comment by DiJu519** [comment]
@khmarbaise 

Sounds like this https://github.com/mojohaus/versions-maven-plugin/commit/0f79ff0669d8ec8638dbfaab23056afd4d6ccb11 needs to be reverted

And https://github.com/mojohaus/versions-maven-plugin/issues/25 needs to be solved another way
